import type { WorkflowNodeDefinition } from './types.js';

export const NODE_DEFINITIONS: WorkflowNodeDefinition[] = [
  {
    type: 'jira.fetchIssue',
    title: 'Get Jira Ticket',
    description: 'Pulls a Jira ticket by key or URL. Accepts "PROJ-123" or a full Jira URL — the key is extracted automatically.',
    useCase: 'The starting point for any workflow that reads from an existing Jira ticket. Paste a ticket URL or key and this node fetches the summary, description, and other fields. No separate extract step needed.',
    category: 'jira',
    configSchema: [
      {
        key: 'configPath',
        label: 'Jira Config File',
        type: 'string',
        required: true,
        defaultValue: '{{vars.configPath}}',
        placeholder: 'data/Jira/config/jira.env',
        hint: 'Path to a .env file containing JIRA_BASE_URL, JIRA_EMAIL, and JIRA_API_TOKEN. Relative to the working directory. Generate an API token at https://id.atlassian.com/manage-profile/security/api-tokens.',
      },
      {
        key: 'issueKey',
        label: 'Ticket URL or Key',
        type: 'string',
        required: true,
        placeholder: 'PROJ-123 or https://.../browse/PROJ-123',
        hint: 'Paste a Jira ticket key (e.g. PROJ-123) or a full URL (e.g. https://yourcompany.atlassian.net/browse/PROJ-123). The key is extracted automatically from URLs. Use {{vars.ticket}} to pull from workflow variables.',
      },
      {
        key: 'fields',
        label: 'Fields to Fetch',
        type: 'string',
        placeholder: 'summary,description,status,priority,issuetype,project,comment,attachment',
        hint: 'Comma-separated Jira field names. Common: summary, description, status, priority, issuetype, project, comment, attachment, assignee, reporter, labels.',
      },
    ],
    outputSchema: [
      { key: 'key', type: 'string', description: 'Ticket key (e.g. PROJ-123)' },
      { key: 'raw', type: 'object', description: 'Full Jira API response — access nested fields via raw.fields.*' },
      { key: 'summary', type: 'string', description: 'Ticket title/summary' },
      { key: 'description', type: 'string', description: 'Ticket description as plain text' },
    ],
  },
  {
    type: 'jira.searchJql',
    title: 'Search Jira',
    description: 'Searches Jira using a JQL query and returns matching tickets.',
    useCase: 'Use to find related tickets, pull recent issues, or gather context for AI. Often placed after Get Jira Ticket to enrich prompts with neighboring work.',
    category: 'jira',
    configSchema: [
      {
        key: 'configPath',
        label: 'Jira Config Path',
        type: 'string',
        required: true,
        defaultValue: '{{vars.configPath}}',
        placeholder: 'data/Jira/config/jira.env',
        hint: 'Path to a .env file containing JIRA_BASE_URL, JIRA_EMAIL, and JIRA_API_TOKEN. Relative to the working directory.',
      },
      {
        key: 'jql',
        label: 'JQL',
        type: 'string',
        required: true,
        placeholder: 'project = CEQ ORDER BY updated DESC',
        multiline: true,
        hint: 'Jira Query Language expression. Examples: "project = CEQ", "assignee = currentUser()", "status = \'In Progress\'". Found in Jira under Filters > Advanced search. See Atlassian JQL documentation for full syntax.',
      },
      {
        key: 'maxResults',
        label: 'Max Results',
        type: 'number',
        defaultValue: 10,
        hint: 'Maximum number of issues to return. Jira\'s API default maximum is 100. Use lower values for faster responses.',
      },
      {
        key: 'fields',
        label: 'Fields CSV',
        type: 'string',
        placeholder: 'summary,description,status,priority,issuetype,project',
        hint: 'Comma-separated Jira field names to include in results. Fewer fields = faster response. Common: summary, description, status, priority, issuetype, project, assignee, reporter.',
      },
    ],
    outputSchema: [
      { key: 'jql', type: 'string', description: 'The JQL query that was run' },
      { key: 'count', type: 'number', description: 'Number of issues returned' },
      { key: 'issues', type: 'array', description: 'Array of matching Jira issues' },
    ],
  },
  {
    type: 'jira.collectImageRefs',
    title: 'Get Ticket Images',
    description: 'Extracts image/attachment URLs from a fetched Jira ticket.',
    useCase: 'Use after Get Jira Ticket when you need to analyze screenshots or diagrams. Pair with Vision Extract to read image content.',
    category: 'jira',
    configSchema: [
      {
        key: 'issueRaw',
        label: 'Issue Raw JSON',
        type: 'json',
        required: true,
        hint: 'The raw Jira issue JSON from a Fetch Jira Issue node. Use a {{ref}} like {{fetchIssue.raw}} to pass the full API response. This node scans the attachments for image content types.',
      },
    ],
    outputSchema: [
      { key: 'count', type: 'number', description: 'Number of images found' },
      { key: 'refs', type: 'array', description: 'Array of image URLs/paths' },
    ],
  },
  {
    type: 'spec.input',
    title: 'Write a Spec',
    description: 'Define a project or task specification from scratch — used to generate Jira tickets when you don\'t have an existing ticket.',
    useCase: 'Use as the starting node when creating tickets from scratch. Fill in the fields (objective, scope, constraints, etc.) and connect to an AI node to generate ticket JSON.',
    category: 'spec',
    configSchema: [
      {
        key: 'title',
        label: 'Spec Title',
        type: 'string',
        required: true,
        placeholder: 'Project or initiative name',
        hint: 'A short title for this specification. Used as a heading when the spec is passed to AI nodes. Example: "User Authentication Overhaul".',
      },
      {
        key: 'objective',
        label: 'Objective',
        type: 'string',
        placeholder: 'What this work must achieve',
        multiline: true,
        hint: 'Describe what this work should accomplish. Focus on outcomes, not implementation. Example: "Enable SSO login via SAML 2.0 for enterprise customers".',
      },
      {
        key: 'scope',
        label: 'Scope',
        type: 'string',
        placeholder: 'In-scope and out-of-scope details',
        multiline: true,
        hint: 'Define boundaries for the work. List what is explicitly in-scope and out-of-scope to prevent scope creep. Example: "In: backend API, login page. Out: mobile app, password reset".',
      },
      {
        key: 'constraints',
        label: 'Constraints',
        type: 'string',
        placeholder: 'Timeline, architecture, policy constraints',
        multiline: true,
        hint: 'Any hard constraints such as deadlines, technology requirements, compliance rules, or architecture decisions that must be respected.',
      },
      {
        key: 'acceptanceCriteria',
        label: 'Acceptance Criteria',
        type: 'string',
        placeholder: 'Definition of done',
        multiline: true,
        hint: 'Measurable conditions that must be met for the work to be considered done. Use "Given/When/Then" or bullet-point format.',
      },
      {
        key: 'deliverables',
        label: 'Deliverables',
        type: 'string',
        placeholder: 'Expected outputs and milestones',
        multiline: true,
        hint: 'Concrete artifacts or milestones expected from this work. Example: "API endpoints documented, unit tests passing, staging deployment".',
      },
      {
        key: 'notes',
        label: 'Notes',
        type: 'string',
        placeholder: 'Additional context',
        multiline: true,
        hint: 'Any additional context, links, or background information that may be useful. This is freeform text appended to the spec.',
      },
    ],
    outputSchema: [
      { key: 'title', type: 'string', description: 'Spec title' },
      { key: 'specText', type: 'string', description: 'Composed spec text for AI consumption' },
      { key: 'empty', type: 'boolean', description: 'Whether spec content is empty' },
    ],
  },
  {
    type: 'azuredevops.readRepoContext',
    title: 'Pull Repo Code',
    description: 'Samples files from an Azure DevOps repository so AI nodes can reference real code in your project.',
    useCase: 'Place before an AI node when generated tickets need to reference actual code. Files are sampled and injected into the AI prompt. Use filters to focus on relevant files.',
    category: 'ado',
    configSchema: [
      {
        key: 'adoConfigPath',
        label: 'ADO Config File',
        type: 'string',
        defaultValue: '{{vars.adoConfigPath}}',
        placeholder: 'data/ADO/config/ado.env',
        hint: 'Path to the encrypted ADO config file containing organization URL and PAT. Click the "ADO Config" button in the Variables pane to manage credentials. Use {{vars.adoConfigPath}} to pull from workflow variables.',
      },
      {
        key: 'repoUrl',
        label: 'Repo URL',
        type: 'string',
        defaultValue: '{{vars.adoRepoUrl}}',
        placeholder: 'https://org.visualstudio.com/Project/_git/Repo',
        hint: 'Paste a full ADO repo URL to auto-set project and repository. Supports: https://org.visualstudio.com/Project/_git/Repo or https://dev.azure.com/org/Project/_git/Repo. If set, overrides the project and repository fields below. Defaults to {{vars.adoRepoUrl}}.',
      },
      {
        key: 'project',
        label: 'Project',
        type: 'string',
        placeholder: 'Azure DevOps project name',
        hint: 'The Azure DevOps project name. Auto-filled if Repo URL is provided. Found in Azure DevOps under Organization Settings > Projects, or in the URL after the org name: https://dev.azure.com/org/PROJECT-NAME.',
      },
      {
        key: 'repository',
        label: 'Repository',
        type: 'string',
        placeholder: 'Repository name or ID',
        hint: 'Repository name (or GUID). Auto-filled if Repo URL is provided. Found in Azure DevOps under Repos > Files — the repo name is shown in the dropdown at the top. Case-sensitive.',
      },
      {
        key: 'branch',
        label: 'Branch',
        type: 'string',
        defaultValue: 'main',
        placeholder: 'main',
        hint: 'Git branch name to sample files from. Common values: "main", "master", "develop". Found in Azure DevOps under Repos > Branches.',
      },
      {
        key: 'path',
        label: 'Path',
        type: 'string',
        defaultValue: '/',
        placeholder: '/',
        hint: 'Repository path to start sampling from. Use "/" for the root, or a subfolder like "/src". Files are recursively discovered from this path.',
      },
      {
        key: 'maxFiles',
        label: 'Max Files',
        type: 'number',
        defaultValue: 6,
        hint: 'Maximum number of files to sample from the repository. Higher values provide more context but increase processing time and token usage.',
      },
      {
        key: 'maxCharsPerFile',
        label: 'Max Chars/File',
        type: 'number',
        defaultValue: 2500,
        hint: 'Maximum characters to read from each sampled file. Files longer than this are truncated. Increase for larger files, decrease to save tokens.',
      },
      {
        key: 'fileNameFilter',
        label: 'File Name Filter',
        type: 'string',
        placeholder: 'email,template,notification',
        hint: 'Comma-separated terms to filter by file path/name. Only files whose path contains at least one term will be sampled. Case-insensitive. Example: "email,template" matches /src/email-service.ts and /templates/welcome.html. Leave empty to include all files.',
      },
      {
        key: 'contentFilter',
        label: 'File Content Filter',
        type: 'string',
        placeholder: 'sendEmail,SmtpClient,mailConfig',
        hint: 'Comma-separated terms to filter by file content. After file name filtering, only files containing at least one of these terms in their source code are kept. Case-insensitive. Example: "sendEmail,SmtpClient" keeps only files that reference those terms. Leave empty to skip content filtering.',
      },
    ],
    outputSchema: [
      { key: 'connected', type: 'boolean', description: 'Whether repo access succeeded' },
      { key: 'summary', type: 'string', description: 'Combined sampled code context' },
      { key: 'files', type: 'array', description: 'Sampled files with content excerpts' },
      { key: 'reason', type: 'string', description: 'Skip/failure reason when unavailable' },
    ],
  },
  {
    type: 'azuredevops.createPullRequest',
    title: 'Create Pull Request',
    description: 'Creates a feature branch in Azure DevOps, pushes code changes from a ticket description, and opens a PR.',
    useCase: 'Use after Create Jira Tickets to push AI-generated code to a feature branch and open a PR. Supports dry-run mode to preview first.',
    category: 'ado',
    configSchema: [
      {
        key: 'adoConfigPath',
        label: 'ADO Config File',
        type: 'string',
        defaultValue: '{{vars.adoConfigPath}}',
        placeholder: 'data/ADO/config/ado.env',
        hint: 'Path to the encrypted ADO config file containing organization URL and PAT. Click the "ADO Config" button in the Variables pane to manage credentials.',
      },
      {
        key: 'repoUrl',
        label: 'Repo URL',
        type: 'string',
        defaultValue: '{{vars.adoRepoUrl}}',
        placeholder: 'https://org.visualstudio.com/Project/_git/Repo',
        hint: 'Paste a full ADO repo URL to auto-set project and repository. If set, overrides the project and repository fields below. Defaults to {{vars.adoRepoUrl}}.',
      },
      {
        key: 'project',
        label: 'Project',
        type: 'string',
        placeholder: 'Project name',
        hint: 'Azure DevOps project name. Auto-filled if Repo URL is provided. Should match the readRepoContext node.',
      },
      {
        key: 'repository',
        label: 'Repository',
        type: 'string',
        required: true,
        placeholder: 'Repository name',
        hint: 'Repository name or GUID. Should match the readRepoContext node.',
      },
      {
        key: 'sourceBranch',
        label: 'Source Branch',
        type: 'string',
        defaultValue: 'main',
        placeholder: 'main',
        hint: 'Base branch to create the feature branch from and target for the PR.',
      },
      {
        key: 'ticketKey',
        label: 'Ticket Key',
        type: 'string',
        required: true,
        placeholder: '{{createIssues.created}}',
        hint: 'Jira ticket key (e.g. CEQ-123). Used in branch name and PR title.',
      },
      {
        key: 'ticketSummary',
        label: 'Ticket Summary',
        type: 'string',
        required: true,
        placeholder: '{{createIssues.created}}',
        hint: 'Ticket summary text. Used to generate the feature branch name.',
      },
      {
        key: 'ticketDescription',
        label: 'Ticket Description',
        type: 'string',
        required: true,
        multiline: true,
        placeholder: '{{generateTickets.text}}',
        hint: 'Full ticket description containing code blocks. Expected format: "File: path/to/file.ext" followed by a fenced code block with the complete file content.',
      },
      {
        key: 'jiraConfigPath',
        label: 'Jira Config Path',
        type: 'string',
        placeholder: '{{vars.configPath}}',
        hint: 'Path to Jira config file. Used to build the Jira ticket link in the PR description. Optional — if omitted, the link is skipped.',
      },
      {
        key: 'dryRun',
        label: 'Dry Run',
        type: 'boolean',
        defaultValue: true,
        hint: 'When enabled, simulates the PR creation without calling Azure DevOps APIs. Disable to create real branches and PRs.',
      },
    ],
    outputSchema: [
      { key: 'created', type: 'boolean', description: 'Whether the PR was created' },
      { key: 'dryRun', type: 'boolean', description: 'Whether this was a dry run' },
      { key: 'branchName', type: 'string', description: 'Feature branch name' },
      { key: 'prId', type: 'number', description: 'Pull request ID' },
      { key: 'prUrl', type: 'string', description: 'Pull request URL' },
      { key: 'prTitle', type: 'string', description: 'Pull request title' },
      { key: 'filesChanged', type: 'number', description: 'Number of files changed' },
      { key: 'warning', type: 'string', description: 'Warning if no code changes found' },
    ],
  },
  {
    type: 'jira.addComment',
    title: 'Comment on Ticket',
    description: 'Adds a comment to an existing Jira ticket. Supports markdown formatting.',
    useCase: 'Use at the end of a workflow to post results back to Jira — link a PR URL, post a summary, or note that sub-tickets were created.',
    category: 'jira',
    configSchema: [
      {
        key: 'configPath',
        label: 'Jira Config Path',
        type: 'string',
        required: true,
        defaultValue: '{{vars.configPath}}',
        placeholder: 'data/Jira/config/jira.env',
        hint: 'Path to .env file with JIRA_BASE_URL, JIRA_EMAIL, JIRA_API_TOKEN.',
      },
      {
        key: 'issueKey',
        label: 'Issue Key',
        type: 'string',
        required: true,
        placeholder: '{{createIssues.created}}',
        hint: 'Jira issue key to comment on (e.g. CEQ-123). Reference from a previous node.',
      },
      {
        key: 'comment',
        label: 'Comment Text',
        type: 'string',
        required: true,
        multiline: true,
        placeholder: 'PR created: {{createPR.prUrl}}',
        hint: 'Comment text in markdown. Supports **bold**, bullet lists, code blocks, tables, and links.',
      },
      {
        key: 'outputFormat',
        label: 'Output Format',
        type: 'string',
        required: false,
        options: ['adf', 'plain'],
        defaultValue: 'adf',
        hint: 'Format for the Jira comment. "adf" converts markdown to Atlassian Document Format (tables, bold, links). "plain" posts as unformatted text.',
      },
    ],
    outputSchema: [
      { key: 'issueKey', type: 'string', description: 'Issue key commented on' },
      { key: 'commentId', type: 'string', description: 'Jira comment ID' },
      { key: 'created', type: 'boolean', description: 'Always true on success' },
    ],
  },
  {
    type: 'jira.updateIssue',
    title: 'Update Jira Ticket',
    description: 'Updates a Jira ticket by replacing its description or adding a comment. Accepts markdown (converted to ADF). Can re-embed original image attachments.',
    useCase: 'Place at the end of a review workflow. Use "update" mode to replace the description with refined content, or "comment" mode to add the refinement as a comment while keeping the original ticket intact.',
    category: 'jira',
    configSchema: [
      {
        key: 'configPath',
        label: 'Jira Config Path',
        type: 'string',
        required: true,
        defaultValue: '{{vars.configPath}}',
        placeholder: 'data/Jira/config/jira.env',
        hint: 'Path to .env file with JIRA_BASE_URL, JIRA_EMAIL, JIRA_API_TOKEN.',
      },
      {
        key: 'issueKey',
        label: 'Issue Key',
        type: 'string',
        required: true,
        placeholder: '{{seed.key}}',
        hint: 'Jira issue key to update (e.g. CEQ-123). Reference from a previous node.',
      },
      {
        key: 'mode',
        label: 'Mode',
        type: 'string',
        options: ['update', 'comment'],
        defaultValue: 'update',
        hint: '"update" replaces the ticket description. "comment" adds the content as a comment, preserving the original description.',
      },
      {
        key: 'summary',
        label: 'Summary',
        type: 'string',
        placeholder: '{{seed.summary}}',
        hint: 'New summary/title for the ticket. Leave empty to keep the current summary. Only used in "update" mode.',
      },
      {
        key: 'description',
        label: 'Description / Comment Body',
        type: 'string',
        multiline: true,
        required: true,
        placeholder: '{{synthesizeAi.text}}',
        hint: 'Markdown content. In "update" mode this replaces the description. In "comment" mode this becomes the comment body.',
      },
      {
        key: 'imageAttachments',
        label: 'Original Image Attachments',
        type: 'string',
        placeholder: '{{imageRefs.attachments}}',
        hint: 'Optional. Attachment metadata array from jira.collectImageRefs. Images are re-embedded inline using ADF media nodes so they appear in the updated description or comment.',
      },
      {
        key: 'dryRun',
        label: 'Dry Run',
        type: 'boolean',
        placeholder: 'false',
        hint: 'When true, shows the exact text that would be sent to Jira without actually updating the ticket.',
      },
    ],
    outputSchema: [
      { key: 'issueKey', type: 'string', description: 'Issue key that was updated' },
      { key: 'updated', type: 'boolean', description: 'True on success (false in dry run)' },
      { key: 'dryRun', type: 'boolean', description: 'Whether this was a dry run' },
      { key: 'mode', type: 'string', description: '"update" or "comment"' },
      { key: 'description', type: 'string', description: 'The full description/comment text that was (or would be) sent' },
      { key: 'updatedFields', type: 'array', description: 'List of field names that were updated' },
    ],
  },
  {
    type: 'jira.createIssues',
    title: 'Create Jira Tickets',
    description: 'Creates one or more Jira tickets from AI-generated JSON. Supports dry-run to preview before creating.',
    useCase: 'Place after an AI node that outputs ticket JSON. In dry-run mode, tickets are simulated so you can review before creating. Can auto-move tickets to a target status column.',
    category: 'jira',
    configSchema: [
      {
        key: 'configPath',
        label: 'Jira Config Path',
        type: 'string',
        required: true,
        defaultValue: '{{vars.configPath}}',
        placeholder: 'data/Jira/config/jira.env',
        hint: 'Path to a .env file containing JIRA_BASE_URL, JIRA_EMAIL, and JIRA_API_TOKEN. Relative to the working directory.',
      },
      {
        key: 'projectKey',
        label: 'Project Key',
        type: 'string',
        required: true,
        placeholder: 'CEQ',
        hint: 'The short project key in Jira (e.g. "CEQ", "PROJ"). Found in Jira under Project Settings > Details, or visible as the prefix in any ticket key like CEQ-123. Must be uppercase letters only.',
      },
      {
        key: 'board',
        label: 'Board/Workspace',
        type: 'string',
        placeholder: 'Team board label',
        hint: 'The Jira board or workspace name where tickets should appear. Found in Jira under Boards menu in the left sidebar. This is the display name (e.g. "Sprint Board", "Kanban Board"). Optional — if omitted, tickets go to the project\'s default board.',
      },
      {
        key: 'issueTypeName',
        label: 'Issue Type',
        type: 'string',
        defaultValue: 'Task',
        placeholder: 'Task',
        hint: 'Jira issue type name. Common values: "Task", "Story", "Bug", "Epic", "Sub-task". Must match an issue type configured in the target project. Found in Jira under Project Settings > Issue types.',
      },
      {
        key: 'tickets',
        label: 'Tickets JSON or Ref',
        type: 'string',
        required: true,
        placeholder: '{{generateTickets.text}}',
        multiline: true,
        hint: 'A JSON array of ticket objects, or a {{ref}} to a previous node\'s output containing the JSON. Each object needs at least a "summary" field. Example: [{"summary":"Set up CI","description":"Configure pipeline"}]. Usually referenced from an AI node output.',
      },
      {
        key: 'labels',
        label: 'Default Labels',
        type: 'string',
        placeholder: 'auto-generated,planning',
        hint: 'Comma-separated labels to apply to all created issues. Labels must already exist in your Jira project, or Jira will auto-create them. Found in Jira under Project Settings > Labels. Example: "auto-generated,sprint-5".',
      },
      {
        key: 'components',
        label: 'Default Components',
        type: 'string',
        placeholder: 'Backend,Frontend',
        hint: 'Comma-separated component names to assign to all created issues. Components must already exist in the project. Found in Jira under Project Settings > Components. Example: "Backend,Frontend,API".',
      },
      {
        key: 'dryRun',
        label: 'Dry Run',
        type: 'boolean',
        defaultValue: true,
        hint: 'When enabled (default), tickets are simulated but not actually created in Jira. Disable this to create real tickets. Recommended: test with dry run first, then toggle off.',
      },
      {
        key: 'ticketCount',
        label: 'Ticket Count',
        type: 'number',
        defaultValue: 6,
        hint: 'Suggested number of tickets for the AI to generate. This is guidance passed to the prompt — the AI may produce more or fewer depending on the spec complexity.',
      },
      {
        key: 'targetStatus',
        label: 'Target Status',
        type: 'string',
        placeholder: 'To Do',
        hint: 'After creating each ticket, transition it to this status column. Common values: "To Do", "In Progress", "Selected for Development". Must match an available transition name in the project workflow. Leave empty to keep the default status (usually Backlog). Found in Jira board columns or under Project Settings > Workflows.',
      },
    ],
    outputSchema: [
      { key: 'dryRun', type: 'boolean', description: 'Whether issues were simulated only' },
      { key: 'createdCount', type: 'number', description: 'Number of issues created/simulated' },
      { key: 'created', type: 'array', description: 'Created issue keys/details' },
      { key: 'warning', type: 'string', description: 'Warning when no tickets were parsed' },
    ],
  },
  {
    type: 'ai.runPrompt',
    title: 'AI Generate',
    description: 'Sends a prompt to an AI model and returns the response. Use {{refs}} to inject data from earlier nodes into the prompt.',
    useCase: 'The main AI node. Use it to generate plans, ticket JSON, summaries, or code. Upstream node outputs are automatically available — reference them with {{nodeId.field}} in the prompt.',
    category: 'ai',
    configSchema: [
      {
        key: 'model',
        label: 'Model Tier',
        type: 'string',
        defaultValue: 'sonnet',
        options: ['haiku', 'sonnet', 'opus'],
        hint: 'AI model tier to use. "haiku" (fastest, cheapest), "sonnet" (balanced), "opus" (most capable, slowest). Use haiku for simple transforms, sonnet for general tasks, opus for complex reasoning.',
      },
      {
        key: 'prompt',
        label: 'Prompt',
        type: 'string',
        required: true,
        placeholder: 'Prompt text with optional {{refs}}',
        multiline: true,
        hint: 'The prompt sent to the AI model. Use {{nodeId.outputKey}} syntax to inject outputs from previous nodes. Example: "Summarize this issue: {{fetchIssue.description}}". Supports multi-line text.',
      },
      {
        key: 'timeoutMs',
        label: 'Timeout (ms)',
        type: 'number',
        defaultValue: 240000,
        hint: 'Maximum time in milliseconds to wait for the AI response. Default is 240000 (4 minutes). Increase for complex prompts or opus-tier models that may take longer.',
      },
      {
        key: 'interactiveClarification',
        label: 'Interactive Clarification',
        type: 'boolean',
        defaultValue: false,
        hint: 'When enabled, an interactive chat session opens before the AI prompt runs. The user can answer clarifying questions, and the chat transcript is prepended to the prompt for refined context.',
      },
    ],
    outputSchema: [
      { key: 'model', type: 'string', description: 'Model tier used' },
      { key: 'text', type: 'string', description: 'AI response text' },
      { key: 'durationMs', type: 'number', description: 'Execution time in ms' },
      { key: 'warning', type: 'string', description: 'Warning message if any' },
    ],
  },
  {
    type: 'image.visionExtract',
    title: 'Read Image (Vision)',
    description: 'Analyzes an image using AI vision — extracts text (OCR), describes diagrams, reads screenshots.',
    useCase: 'Use after Get Ticket Images to analyze screenshots, diagrams, or wireframes attached to tickets. The extracted text feeds into downstream AI prompts.',
    category: 'image',
    configSchema: [
      {
        key: 'model',
        label: 'Model Tier',
        type: 'string',
        defaultValue: 'sonnet',
        options: ['haiku', 'sonnet', 'opus'],
        hint: 'AI model tier for vision analysis. "sonnet" recommended for most images. "opus" for complex diagrams or dense text. "haiku" for simple screenshots.',
      },
      {
        key: 'jiraConfigPath',
        label: 'Jira Config Path',
        type: 'string',
        placeholder: 'data/Jira/config/jira.env (required when imagePath is URL)',
        hint: 'Path to Jira .env config — only needed when the image is a Jira attachment URL (requires auth headers to download). Not needed for local file paths.',
      },
      {
        key: 'imagePath',
        label: 'Image File Path',
        type: 'string',
        required: true,
        placeholder: '{{imageRefs.refs}} or /absolute/path/to/image.png',
        hint: 'Path to a local image file, or a {{ref}} to image URLs from a Collect Image Refs node. Supports PNG, JPG, GIF, WebP. For multiple images, pass an array ref like {{imageRefs.refs}}.',
      },
      {
        key: 'seedSummary',
        label: 'Seed Summary',
        type: 'string',
        placeholder: 'Optional context',
        hint: 'Optional context text provided to the AI alongside the image. Helps the model understand what to look for. Example: "This is a screenshot of the login page error state".',
      },
      {
        key: 'timeoutMs',
        label: 'Timeout (ms)',
        type: 'number',
        defaultValue: 240000,
        hint: 'Maximum time in milliseconds to wait for vision analysis. Default is 240000 (4 minutes). Increase for large images or multiple images.',
      },
    ],
    outputSchema: [
      { key: 'model', type: 'string', description: 'Model tier used' },
      { key: 'imageCount', type: 'number', description: 'Number of images processed' },
      { key: 'imagePath', type: 'string', description: 'Local path of first image' },
      { key: 'sourceUrl', type: 'string', description: 'Original URL of first image' },
      { key: 'images', type: 'array', description: 'Array of per-image analysis results' },
      { key: 'analysis', type: 'string', description: 'Merged OCR/vision analysis text' },
      { key: 'warning', type: 'string', description: 'Warning message if any' },
    ],
  },
  {
    type: 'transform.template',
    title: 'Compose Text',
    description: 'Builds text by combining {{refs}} from earlier nodes into a template. Useful for formatting reports or composing complex prompts.',
    useCase: 'Use when you need to merge outputs from multiple nodes into one text block. Note: the AI Generate node already resolves {{refs}} in its prompt, so you only need this node for non-AI text composition or multi-source formatting.',
    category: 'transform',
    configSchema: [
      {
        key: 'template',
        label: 'Template',
        type: 'string',
        required: true,
        multiline: true,
        hint: 'A text template with {{nodeId.outputKey}} placeholders that get replaced with values from previous nodes. Example: "Issue {{fetch.key}}: {{fetch.summary}}". Supports multi-line output.',
      },
    ],
    outputSchema: [
      { key: 'content', type: 'string', description: 'Rendered template text' },
    ],
  },
  {
    type: 'io.readFile',
    title: 'Read File',
    description: 'Loads a text file from disk. The content can be referenced by downstream nodes via {{nodeId.content}}.',
    useCase: 'Use to load process guides, prompt templates, or config files. The content is available to AI nodes via {{refs}} — e.g. {{guide.content}}.',
    category: 'io',
    configSchema: [
      {
        key: 'path',
        label: 'File Path',
        type: 'string',
        required: true,
        placeholder: 'data/Skills/generic/process-guide.md',
        hint: 'Path to the file to read, relative to the working directory or absolute. Must be a UTF-8 text file. Example: "config/prompts/template.md" or "/Users/me/docs/spec.txt".',
      },
    ],
    outputSchema: [
      { key: 'path', type: 'string', description: 'Absolute file path read' },
      { key: 'content', type: 'string', description: 'File contents (UTF-8)' },
      { key: 'bytes', type: 'number', description: 'File size in bytes' },
    ],
  },
  {
    type: 'io.writeFile',
    title: 'Save to File',
    description: 'Writes text or JSON to a file on disk. Supports pretty-printing JSON.',
    useCase: 'Typically the last node — saves workflow results to disk. The file is auto-loaded into the Workflow Output viewer after execution.',
    category: 'io',
    configSchema: [
      {
        key: 'path',
        label: 'Output Path',
        type: 'string',
        required: true,
        placeholder: 'data/Output/...',
        hint: 'File path to write to, relative to the working directory or absolute. Parent directories are created automatically. Example: "output/results.json" or "reports/summary.md".',
      },
      {
        key: 'content',
        label: 'Content',
        type: 'string',
        required: true,
        multiline: true,
        hint: 'The text content to write. Use {{nodeId.outputKey}} refs to insert outputs from previous nodes. Example: "{{aiPrompt.text}}" to write an AI response to disk.',
      },
      {
        key: 'prettyJson',
        label: 'Pretty JSON',
        type: 'boolean',
        defaultValue: false,
        hint: 'When enabled, if the content is valid JSON it will be formatted with 2-space indentation before writing. Useful when saving structured AI output.',
      },
    ],
    outputSchema: [
      { key: 'path', type: 'string', description: 'Absolute path of written file' },
      { key: 'bytes', type: 'number', description: 'Bytes written' },
      { key: 'written', type: 'boolean', description: 'Always true on success' },
    ],
  },
  {
    type: 'ai.interactiveChat',
    title: 'Review & Refine',
    description: 'Pauses the workflow so you can review the previous node\'s output, chat with AI to request changes, then apply or discard before continuing.',
    useCase: 'Place directly after any node whose output you want to review before it flows downstream. This node automatically reads the previous node\'s primary output (e.g. the AI-generated text from an "AI Generate" node) and shows it in a chat window. You can ask the AI to make changes — when you click "Apply Changes", the upstream output is updated in-place so all downstream nodes see the refined version. Click "Discard" to pass the original through unchanged. No config needed for basic use — just connect it after the node you want to review.',
    category: 'ai',
    configSchema: [
      {
        key: 'systemPrompt',
        label: 'System Prompt (optional)',
        type: 'string',
        multiline: true,
        placeholder: 'Leave blank for auto-generated context',
        hint: 'Optional override for the AI chat personality. When left blank, this node auto-generates a context-aware system prompt based on what\'s upstream and downstream in the workflow. Only set this if you need custom behavior.',
      },
      {
        key: 'greeting',
        label: 'Greeting Message (optional)',
        type: 'string',
        multiline: true,
        placeholder: 'Leave blank for auto-generated greeting',
        hint: 'Optional override for the first message shown when the chat opens. When blank, auto-generates a greeting that describes what was produced upstream and what the next step expects. Use {{refs}} to inject data.',
      },
      {
        key: 'model',
        label: 'Model Tier',
        type: 'string',
        defaultValue: 'sonnet',
        options: ['haiku', 'sonnet', 'opus'],
        hint: 'AI model for the chat and for applying refinements. "sonnet" is recommended for most cases.',
      },
      {
        key: 'maxTurns',
        label: 'Max Turns',
        type: 'number',
        defaultValue: 20,
        hint: 'Maximum chat exchanges before the session auto-closes.',
      },
    ],
    outputSchema: [
      { key: 'text', type: 'string', description: 'The refined (or original) text after review — use {{nodeId.text}} in downstream nodes' },
      { key: 'transcript', type: 'array', description: 'Full chat history as {role, content, timestamp} messages' },
      { key: 'transcriptText', type: 'string', description: 'Chat transcript as plain text' },
      { key: 'turnCount', type: 'number', description: 'Number of user messages sent' },
      { key: 'summary', type: 'string', description: 'AI-generated summary of what was discussed/changed' },
      { key: 'action', type: 'string', description: '"apply" if user applied changes, "discard" if skipped' },
    ],
  },
  {
    type: 'web.fetchUrl',
    title: 'Fetch Web Page',
    description: 'Fetches the content of one or more URLs and returns the page text as markdown. Useful for following links found in tickets.',
    useCase: 'Place after a Jira ticket node to follow external links (release notes, deprecation notices, Stack Overflow posts). The fetched content feeds into AI nodes for analysis.',
    category: 'web',
    configSchema: [
      {
        key: 'urls',
        label: 'URLs',
        type: 'string',
        required: true,
        multiline: true,
        placeholder: 'https://example.com/notice\nhttps://stackoverflow.com/questions/...',
        hint: 'One or more URLs to fetch, one per line or comma-separated. Use {{refs}} to inject URLs extracted from a ticket. HTTPS only — authenticated/private pages will fail.',
      },
      {
        key: 'extractPrompt',
        label: 'Extraction Prompt',
        type: 'string',
        multiline: true,
        defaultValue: 'Extract all key facts, changes, dates, and technical details from this page. Return structured plain text.',
        hint: 'Prompt sent to a small AI model to summarize each fetched page. Keep it focused on what you need — the raw HTML is converted to markdown first, then the model extracts the relevant content.',
      },
      {
        key: 'timeoutMs',
        label: 'Timeout (ms)',
        type: 'number',
        defaultValue: 30000,
        hint: 'Maximum time in milliseconds per URL fetch. Default 30 seconds.',
      },
    ],
    outputSchema: [
      { key: 'pages', type: 'array', description: 'Array of {url, content, error?} for each fetched URL' },
      { key: 'count', type: 'number', description: 'Number of pages successfully fetched' },
      { key: 'content', type: 'string', description: 'Combined content from all pages (for use in downstream prompts)' },
    ],
  },
  {
    type: 'ado.codeSearch',
    title: 'Search ADO Code',
    description: 'Searches Azure DevOps code across one or more repositories using a text query. Returns matching file paths and code snippets. Automatically retries with AI-refined queries if the first search returns no results.',
    useCase: 'Place after an AI planning node in research workflows. The AI suggests search terms (e.g. API names, library imports, config keys), and this node finds matching code across your ADO repos. The built-in retry mechanism means you never bail on the first empty result.',
    category: 'ado',
    configSchema: [
      {
        key: 'adoConfigPath',
        label: 'ADO Config File',
        type: 'string',
        defaultValue: '{{vars.adoConfigPath}}',
        placeholder: 'data/ADO/config/ado.env',
        hint: 'Path to the encrypted ADO config file containing organization URL and PAT. Click the "ADO Config" button in the Variables pane to manage credentials.',
      },
      {
        key: 'repoUrl',
        label: 'Scope (Repo URL / Project)',
        type: 'string',
        placeholder: 'https://org.visualstudio.com/Project/_git/Repo',
        hint: 'Controls search scope. Paste a full repo URL to search one repo, a project URL to search all repos in a project, or a project name. Leave empty to search the entire org. Examples: "https://org.visualstudio.com/My Project/_git/MyRepo" → searches MyRepo only. "https://org.visualstudio.com/My Project" → searches all repos in My Project. "My Project" → same. Empty → all repos in org.',
      },
      {
        key: 'query',
        label: 'Search Query',
        type: 'string',
        required: true,
        multiline: true,
        placeholder: '{{seed.summary}} OR {{seed.key}}',
        hint: 'Code search query. Supports keywords, exact phrases ("quoted"), and boolean operators (AND, OR, NOT). Reference upstream nodes to build dynamic queries — e.g. {{seed.summary}} for a Jira ticket summary, {{seed.key}} for the ticket key, or {{planAi.text}} for AI-generated search terms. When connected after a Jira node, try: {{seed.summary}} to search for code related to the ticket.',
      },
      {
        key: 'maxResults',
        label: 'Max Results',
        type: 'number',
        defaultValue: 25,
        hint: 'Maximum number of code matches to return per query.',
      },
      {
        key: 'maxRetries',
        label: 'Max Retries',
        type: 'number',
        defaultValue: 2,
        hint: 'If the search returns no results, AI will suggest refined queries and retry up to this many times. Set to 0 to disable retry.',
      },
      {
        key: 'searchContext',
        label: 'Research Context',
        type: 'string',
        multiline: true,
        placeholder: '{{researchAi.text}}',
        hint: 'Context about what you are researching — used by the AI retry mechanism to refine queries when no results are found. Reference an upstream AI node (e.g. {{researchAi.text}}) or Jira ticket (e.g. {{seed.summary}} — {{seed.description}}) so the retrier understands what to search for.',
      },
      {
        key: 'model',
        label: 'Retry Model',
        type: 'string',
        defaultValue: 'haiku',
        options: ['haiku', 'sonnet', 'opus'],
        hint: 'AI model used to generate refined search queries on retry. Haiku is sufficient for this.',
      },
    ],
    outputSchema: [
      { key: 'results', type: 'array', description: 'Array of {filePath, repository, snippet, url} matches' },
      { key: 'count', type: 'number', description: 'Total matches found across all query attempts' },
      { key: 'queries', type: 'array', description: 'List of queries that were tried (initial + retries)' },
      { key: 'summary', type: 'string', description: 'Formatted summary of all matches for AI consumption' },
    ],
  },
  {
    type: 'ado.deepCodeSearch',
    title: 'Deep ADO Code Search',
    description: 'Performs exhaustive multi-query code search across all Azure DevOps repositories. AI generates a batch of targeted search terms from research context (API names, config keys, import statements, version strings), runs each one, reviews results, and generates follow-up queries to ensure full coverage.',
    useCase: 'Use instead of basic ADO Code Search when you need to scan an entire organization for specific patterns — e.g. finding all systems affected by an API deprecation. Searches ALL repos (no single-repo filter) and uses multiple targeted queries like a human researcher would.',
    category: 'ado',
    configSchema: [
      {
        key: 'adoConfigPath',
        label: 'ADO Config File',
        type: 'string',
        defaultValue: '{{vars.adoConfigPath}}',
        placeholder: 'data/ADO/config/ado.env',
        hint: 'Path to the encrypted ADO config file containing organization URL and PAT. Click the "ADO Config" button in the Variables pane to manage credentials.',
      },
      {
        key: 'repoUrl',
        label: 'Scope (Repo URL / Project)',
        type: 'string',
        placeholder: 'https://org.visualstudio.com/Project/_git/Repo',
        hint: 'Controls search scope. Paste a full repo URL to search one repo, a project URL to search all repos in a project, or a project name. Leave empty to search the entire org. Examples: "https://org.visualstudio.com/My Project/_git/MyRepo" → searches MyRepo only. "My Project" → searches all repos in that project. Empty → searches entire org.',
      },
      {
        key: 'searchContext',
        label: 'Research Context',
        type: 'string',
        required: true,
        multiline: true,
        placeholder: '{{researchAi.text}}',
        hint: 'Context for AI to generate search queries from. Reference an upstream AI node (e.g. {{researchAi.text}}, {{planSearch.text}}) or combine Jira ticket fields (e.g. {{seed.summary}} — {{seed.description}}). The AI extracts API names, imports, config keys, etc. to build targeted queries.',
      },
      {
        key: 'maxResultsPerQuery',
        label: 'Max Results Per Query',
        type: 'number',
        defaultValue: 10,
        hint: 'Maximum code matches to return per individual query. Keep low (10-15) since we run many queries.',
      },
      {
        key: 'maxRounds',
        label: 'Max Rounds',
        type: 'number',
        defaultValue: 2,
        hint: 'Number of search rounds. Round 1: AI generates initial queries from context. Round 2+: AI reviews findings and generates follow-up queries. More rounds = more thorough but slower.',
      },
      {
        key: 'model',
        label: 'AI Model',
        type: 'string',
        defaultValue: 'haiku',
        options: ['haiku', 'sonnet', 'opus'],
        hint: 'AI model for generating search queries. Haiku is fast and sufficient.',
      },
    ],
    outputSchema: [
      { key: 'results', type: 'array', description: 'Array of {filePath, repository, snippet, url, query} matches, deduplicated by file path + repo' },
      { key: 'count', type: 'number', description: 'Total unique files matched across all queries' },
      { key: 'queries', type: 'array', description: 'All queries that were executed across all rounds' },
      { key: 'rounds', type: 'number', description: 'Number of search rounds completed' },
      { key: 'summary', type: 'string', description: 'Formatted summary of all matches grouped by repository' },
    ],
  },
  {
    type: 'confluence.search',
    title: 'Search Confluence',
    description: 'Searches Confluence pages using CQL (Confluence Query Language) or text. Returns matching page titles, excerpts, and links. Automatically retries with AI-refined queries if the first search returns no results.',
    useCase: 'Place after an AI planning node in research workflows to find relevant documentation, architecture docs, runbooks, or team pages. Uses the same Atlassian auth as your Jira config.',
    category: 'confluence',
    configSchema: [
      {
        key: 'configPath',
        label: 'Jira/Atlassian Config',
        type: 'string',
        required: true,
        defaultValue: '{{vars.configPath}}',
        placeholder: 'data/Jira/config/jira.env',
        hint: 'Path to .env file with JIRA_BASE_URL, JIRA_EMAIL, JIRA_API_TOKEN. Confluence uses the same Atlassian authentication. The base URL should be your Atlassian site (e.g. https://yourcompany.atlassian.net).',
      },
      {
        key: 'query',
        label: 'Search Query',
        type: 'string',
        required: true,
        multiline: true,
        placeholder: 'Microsoft Graph API deprecation',
        hint: 'Text to search for in Confluence. This is used in a CQL text~ query. Use {{refs}} to inject AI-generated search terms.',
      },
      {
        key: 'spaceKey',
        label: 'Space Key',
        type: 'string',
        placeholder: 'Leave blank to search all spaces',
        hint: 'Optional: limit search to a specific Confluence space (e.g. "ENG", "ARCH"). Leave blank to search all spaces.',
      },
      {
        key: 'maxResults',
        label: 'Max Results',
        type: 'number',
        defaultValue: 15,
        hint: 'Maximum number of Confluence pages to return per query.',
      },
      {
        key: 'maxRetries',
        label: 'Max Retries',
        type: 'number',
        defaultValue: 2,
        hint: 'If search returns no results, AI suggests refined queries and retries up to this many times. Set to 0 to disable.',
      },
      {
        key: 'searchContext',
        label: 'Research Context',
        type: 'string',
        multiline: true,
        placeholder: '{{planSearch.text}}',
        hint: 'Context about what you are researching. Used by the AI retry mechanism to generate better alternative queries.',
      },
      {
        key: 'model',
        label: 'Retry Model',
        type: 'string',
        defaultValue: 'haiku',
        options: ['haiku', 'sonnet', 'opus'],
        hint: 'AI model used to generate refined search queries on retry.',
      },
    ],
    outputSchema: [
      { key: 'results', type: 'array', description: 'Array of {title, spaceKey, excerpt, url} matches' },
      { key: 'count', type: 'number', description: 'Total matches found across all query attempts' },
      { key: 'queries', type: 'array', description: 'List of queries that were tried' },
      { key: 'summary', type: 'string', description: 'Formatted summary of all matches for AI consumption' },
    ],
  },
  {
    type: 'slack.sendMessage',
    title: 'Send Slack Message',
    description: 'Posts a message to a Slack channel via an incoming webhook URL. Supports markdown formatting.',
    useCase: 'Use at the end of a workflow to notify a team channel about results — research findings, incident updates, or completed ticket summaries.',
    category: 'slack',
    configSchema: [
      {
        key: 'webhookUrl',
        label: 'Slack incoming webhook URL',
        type: 'string',
        required: true,
        placeholder: 'https://hooks.slack.com/services/T.../B.../xxx',
        hint: 'Create at https://api.slack.com/messaging/webhooks. Store in an env var and reference with {{vars.slackWebhookUrl}}.',
      },
      {
        key: 'channel',
        label: 'Channel override',
        type: 'string',
        placeholder: '#team-alerts',
        hint: 'Optional channel override. Most webhooks are bound to a specific channel already.',
      },
      {
        key: 'message',
        label: 'Message body (supports Slack mrkdwn)',
        type: 'text',
        required: true,
        placeholder: '{{synthesize.text}}',
        hint: 'The message text to post. Supports Slack mrkdwn formatting. Use {{nodeId.field}} to inject upstream output.',
      },
      {
        key: 'username',
        label: 'Bot username',
        type: 'string',
        placeholder: 'Workflow Studio',
        hint: 'Display name for the bot message.',
      },
      {
        key: 'iconEmoji',
        label: 'Bot icon emoji',
        type: 'string',
        placeholder: ':robot_face:',
        hint: 'Emoji to use as the bot avatar.',
      },
    ],
  },
  {
    type: 'slack.readChannel',
    title: 'Read Slack Channel',
    description: 'Reads recent messages from a Slack channel using a Bot token. Useful for gathering context from team discussions.',
    useCase: 'Feed recent channel discussions into an AI node for context — e.g. read the #incidents channel before generating a postmortem.',
    category: 'slack',
    configSchema: [
      {
        key: 'botToken',
        label: 'Slack Bot Token',
        type: 'string',
        required: true,
        placeholder: '{{vars.slackBotToken}}',
        hint: 'Bot token with channels:history scope. Store as env var, never hardcode.',
      },
      {
        key: 'channelId',
        label: 'Channel ID',
        type: 'string',
        required: true,
        placeholder: 'C01ABCDEF23',
        hint: 'The Slack channel ID (not the name). Find it in channel details > About.',
      },
      {
        key: 'limit',
        label: 'Max messages',
        type: 'string',
        placeholder: '20',
        hint: 'Number of recent messages to fetch (default: 20, max: 100).',
      },
    ],
  },
  {
    type: 'github.codeSearch',
    title: 'GitHub Code Search',
    description: 'Searches code across GitHub repositories using the GitHub search API. Finds files matching keywords, function names, or patterns.',
    useCase: 'Search open-source repos or your org\'s GitHub for code patterns, library usage, or configuration files. Complements ADO code search for teams using both platforms.',
    category: 'github',
    configSchema: [
      {
        key: 'query',
        label: 'Search query',
        type: 'string',
        required: true,
        placeholder: 'org:myorg language:terraform azurerm',
        hint: 'GitHub code search query. Supports qualifiers like org:, repo:, language:, path:, filename:.',
      },
      {
        key: 'tokenEnvVar',
        label: 'GitHub token env var',
        type: 'string',
        placeholder: 'GITHUB_TOKEN',
        hint: 'Environment variable containing a GitHub personal access token. Needed for private repos and higher rate limits.',
      },
      {
        key: 'maxResults',
        label: 'Max results',
        type: 'string',
        placeholder: '30',
        hint: 'Maximum number of code matches to return (default: 30).',
      },
      {
        key: 'searchContext',
        label: 'AI search context',
        type: 'string',
        placeholder: '{{planSearch.text}}',
        hint: 'Pass upstream AI context to generate queries automatically (like ado.deepCodeSearch).',
      },
      {
        key: 'model',
        label: 'AI model for query gen',
        type: 'string',
        placeholder: 'haiku',
        hint: 'Model for generating search queries from context. Only used when searchContext is provided.',
        options: ['haiku', 'sonnet', 'opus'],
      },
    ],
  },
  {
    type: 'conditional.gate',
    title: 'Conditional Gate',
    description: 'Passes or blocks data flow based on a condition. Evaluates a simple expression against upstream output and either forwards the data or returns an empty result.',
    useCase: 'Branch your workflow — e.g. only create tickets if the AI found issues, only send Slack alerts if severity is high, or skip PR creation in dry-run mode.',
    category: 'logic',
    configSchema: [
      {
        key: 'field',
        label: 'Field to check',
        type: 'string',
        required: true,
        placeholder: '{{adoSearch.count}}',
        hint: 'The upstream value to evaluate. Use {{nodeId.field}} syntax.',
      },
      {
        key: 'operator',
        label: 'Operator',
        type: 'string',
        required: true,
        placeholder: 'greaterThan',
        hint: 'Comparison operator.',
        options: ['equals', 'notEquals', 'contains', 'notContains', 'greaterThan', 'lessThan', 'isEmpty', 'isNotEmpty', 'matches'],
      },
      {
        key: 'value',
        label: 'Compare value',
        type: 'string',
        placeholder: '0',
        hint: 'The value to compare against. Not needed for isEmpty/isNotEmpty operators.',
      },
      {
        key: 'passThrough',
        label: 'Pass-through field',
        type: 'string',
        placeholder: '{{synthesize.text}}',
        hint: 'Data to forward when the condition passes. If empty, forwards the field value.',
      },
    ],
  },
  {
    type: 'transform.jsonExtract',
    title: 'Extract from JSON',
    description: 'Extracts specific fields from a JSON object using dot-notation paths. Useful for pulling structured data out of AI responses or API results.',
    useCase: 'Extract specific fields from structured AI output — e.g. pull the \'severity\' field from an AI analysis, or extract a list of impacted repos from a search result.',
    category: 'transform',
    configSchema: [
      {
        key: 'input',
        label: 'JSON input',
        type: 'string',
        required: true,
        placeholder: '{{generateTickets.text}}',
        hint: 'The JSON string or object to extract from. Can reference upstream AI output.',
      },
      {
        key: 'paths',
        label: 'Extraction paths',
        type: 'string',
        required: true,
        placeholder: 'tickets[0].summary, severity, impactedSystems',
        hint: 'Comma-separated dot-notation paths to extract. Supports array indexing (items[0]) and nested paths (a.b.c).',
      },
      {
        key: 'outputFormat',
        label: 'Output format',
        type: 'string',
        placeholder: 'object',
        hint: 'How to format the output: \'object\' returns key-value pairs, \'text\' returns a formatted string.',
        options: ['object', 'text'],
      },
    ],
  },
  {
    type: 'notification.email',
    title: 'Send Email',
    description: 'Sends an email via SMTP. Requires SMTP configuration via environment variables.',
    useCase: 'Send workflow results, reports, or alerts via email — e.g. email a weekly sprint summary to stakeholders or notify team leads about security findings.',
    category: 'notification',
    configSchema: [
      {
        key: 'to',
        label: 'To address(es)',
        type: 'string',
        required: true,
        placeholder: 'team@company.com',
        hint: 'Comma-separated recipient email addresses.',
      },
      {
        key: 'subject',
        label: 'Subject',
        type: 'string',
        required: true,
        placeholder: 'Deep Research Report: {{seed.key}}',
        hint: 'Email subject line. Supports {{nodeId.field}} references.',
      },
      {
        key: 'body',
        label: 'Email body',
        type: 'text',
        required: true,
        placeholder: '{{synthesize.text}}',
        hint: 'Email body content. Supports HTML if your SMTP server allows it.',
      },
      {
        key: 'smtpHostEnvVar',
        label: 'SMTP host env var',
        type: 'string',
        placeholder: 'SMTP_HOST',
        hint: 'Environment variable for SMTP hostname (default: SMTP_HOST).',
      },
      {
        key: 'smtpPortEnvVar',
        label: 'SMTP port env var',
        type: 'string',
        placeholder: 'SMTP_PORT',
        hint: 'Environment variable for SMTP port (default: SMTP_PORT, typically 587).',
      },
      {
        key: 'smtpUserEnvVar',
        label: 'SMTP user env var',
        type: 'string',
        placeholder: 'SMTP_USER',
        hint: 'Environment variable for SMTP username.',
      },
      {
        key: 'smtpPassEnvVar',
        label: 'SMTP password env var',
        type: 'string',
        placeholder: 'SMTP_PASS',
        hint: 'Environment variable for SMTP password.',
      },
      {
        key: 'from',
        label: 'From address',
        type: 'string',
        placeholder: 'workflow-studio@company.com',
        hint: 'Sender address. Defaults to SMTP_USER if not specified.',
      },
    ],
  },
];
