import type { WorkflowGraph } from './types.js';

export const JIRA_PLAN_TEMPLATE: WorkflowGraph = {
  id: 'jira-plan-template',
  name: 'Jira Plan',
  description: 'Pulls a Jira ticket plus related issues, then asks AI to produce a numbered implementation plan with owner roles and done criteria. Saves the plan to a file.',
  category: 'Planning & Research',
  nodes: [
    {
      id: 'seed',
      type: 'jira.fetchIssue',
      position: { x: 40, y: 40 },
      config: {
        configPath: '{{vars.configPath}}',
        issueKey: '{{vars.ticket}}',
        fields: 'summary,description,status,priority,issuetype,project,comment,attachment',
      },
    },
    {
      id: 'related',
      type: 'jira.searchJql',
      position: { x: 320, y: 40 },
      config: {
        configPath: '{{vars.configPath}}',
        jql: 'project = "{{seed.raw.fields.project.key}}" AND key != "{{seed.key}}" ORDER BY updated DESC',
        maxResults: '{{vars.relatedLimit}}',
        fields: 'summary,description,status,priority,issuetype,project',
      },
    },
    {
      id: 'planAi',
      type: 'ai.runPrompt',
      position: { x: 600, y: 40 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 240000,
        prompt: [
          'Create an actionable Jira implementation plan.',
          '',
          'JIRA TICKET PLAN',
          '================',
          'Seed: {{seed.key}} - {{seed.summary}}',
          'Description: {{seed.description}}',
          'Related ticket count: {{related.count}}',
          '',
          'Return concise numbered steps with owner roles and done criteria.',
        ].join('\n'),
      },
    },
    {
      id: 'write',
      type: 'io.writeFile',
      position: { x: 880, y: 40 },
      config: {
        path: '{{vars.outputPath}}',
        content: '{{planAi.text}}',
      },
    },
  ],
  edges: [
    { from: 'seed', to: 'related' },
    { from: 'related', to: 'planAi' },
    { from: 'planAi', to: 'write' },
  ],
};

export const JIRA_RESEARCH_TEMPLATE: WorkflowGraph = {
  id: 'jira-research-template',
  name: 'Jira Research',
  description: 'Pulls a Jira ticket, extracts and analyzes attached images via OCR/vision, searches Jira for related tickets, then synthesizes all findings into a research summary with context, risks, dependencies, and next actions. Saves the summary to a file.',
  category: 'Planning & Research',
  nodes: [
    {
      id: 'seed',
      type: 'jira.fetchIssue',
      position: { x: 40, y: 220 },
      config: {
        configPath: '{{vars.configPath}}',
        issueKey: '{{vars.ticket}}',
        fields: 'summary,description,status,priority,issuetype,project,comment,attachment',
      },
    },
    {
      id: 'imageRefs',
      type: 'jira.collectImageRefs',
      position: { x: 320, y: 60 },
      config: {
        issueRaw: '{{seed.raw}}',
      },
    },
    {
      id: 'vision',
      type: 'image.visionExtract',
      position: { x: 600, y: 60 },
      config: {
        model: '{{vars.model}}',
        jiraConfigPath: '{{vars.configPath}}',
        imagePath: '{{imageRefs.refs}}',
        seedSummary: '{{seed.summary}}',
        timeoutMs: 240000,
      },
    },
    {
      id: 'related',
      type: 'jira.searchJql',
      position: { x: 320, y: 380 },
      config: {
        configPath: '{{vars.configPath}}',
        jql: 'project = "{{seed.raw.fields.project.key}}" AND text ~ "{{seed.summary}}" AND key != "{{seed.key}}" ORDER BY updated DESC',
        maxResults: '{{vars.relatedLimit}}',
        fields: 'summary,description,status,priority,issuetype,project',
      },
    },
    {
      id: 'researchAi',
      type: 'ai.runPrompt',
      position: { x: 880, y: 220 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 240000,
        prompt: [
          'You are a senior technical analyst. Produce a comprehensive research summary for the following Jira ticket.',
          '',
          'TICKET:',
          'Key: {{seed.key}}',
          'Summary: {{seed.summary}}',
          'Description:',
          '{{seed.description}}',
          '',
          'ATTACHED IMAGES — OCR / VISION ANALYSIS ({{imageRefs.count}} image(s) found):',
          'The following is extracted text and visual analysis from images attached to this ticket.',
          'If images were found, incorporate their content (OCR text, UI elements, diagrams, error messages, etc.) into your analysis.',
          '',
          '{{vision.analysis}}',
          '',
          'RELATED TICKETS ({{related.count}} found):',
          '{{related.issues}}',
          '',
          'Produce a research summary with the following sections:',
          '',
          '## Context',
          'What this ticket is about, incorporating details from the description and any image analysis.',
          '',
          '## Key Findings',
          'Important details, patterns, or insights from the ticket and related tickets.',
          '',
          '## Risks & Dependencies',
          'Potential risks, blockers, or dependencies identified from the ticket content and related work.',
          '',
          '## Next Actions',
          'Concrete recommended next steps, in priority order.',
          '',
          'Be concise. Every claim should be traceable to the ticket content, image analysis, or related tickets.',
        ].join('\n'),
      },
    },
    {
      id: 'write',
      type: 'io.writeFile',
      position: { x: 1160, y: 220 },
      config: {
        path: '{{vars.outputPath}}',
        content: '{{researchAi.text}}',
      },
    },
  ],
  edges: [
    { from: 'seed', to: 'imageRefs' },
    { from: 'seed', to: 'related' },
    { from: 'imageRefs', to: 'vision' },
    { from: 'vision', to: 'researchAi' },
    { from: 'related', to: 'researchAi' },
    { from: 'researchAi', to: 'write' },
  ],
};

export const JIRA_RESEARCH_ADO_TEMPLATE: WorkflowGraph = {
  id: 'jira-research-ado-template',
  name: 'Jira Research + ADO Code Search',
  description: 'Pulls a Jira ticket, extracts and analyzes attached images, searches for related Jira tickets, then uses an AI research summary to drive an ADO code search across your repositories. Synthesizes all findings — ticket context, image analysis, related tickets, and matching code — into a comprehensive research report.',
  category: 'Planning & Research',
  nodes: [
    {
      id: 'seed',
      type: 'jira.fetchIssue',
      position: { x: 40, y: 220 },
      config: {
        configPath: '{{vars.configPath}}',
        issueKey: '{{vars.ticket}}',
        fields: 'summary,description,status,priority,issuetype,project,comment,attachment',
      },
    },
    {
      id: 'imageRefs',
      type: 'jira.collectImageRefs',
      position: { x: 320, y: 60 },
      config: {
        issueRaw: '{{seed.raw}}',
      },
    },
    {
      id: 'vision',
      type: 'image.visionExtract',
      position: { x: 600, y: 60 },
      config: {
        model: '{{vars.model}}',
        jiraConfigPath: '{{vars.configPath}}',
        imagePath: '{{imageRefs.refs}}',
        seedSummary: '{{seed.summary}}',
        timeoutMs: 240000,
      },
    },
    {
      id: 'related',
      type: 'jira.searchJql',
      position: { x: 320, y: 380 },
      config: {
        configPath: '{{vars.configPath}}',
        jql: 'project = "{{seed.raw.fields.project.key}}" AND text ~ "{{seed.summary}}" AND key != "{{seed.key}}" ORDER BY updated DESC',
        maxResults: '{{vars.relatedLimit}}',
        fields: 'summary,description,status,priority,issuetype,project',
      },
    },
    {
      id: 'researchAi',
      type: 'ai.runPrompt',
      position: { x: 880, y: 220 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 240000,
        prompt: [
          'You are a senior technical analyst. Produce an initial research summary for the following Jira ticket. This summary will be used to drive a code search, so include specific technical terms, API names, class names, config keys, and patterns that might appear in source code.',
          '',
          'TICKET:',
          'Key: {{seed.key}}',
          'Summary: {{seed.summary}}',
          'Description:',
          '{{seed.description}}',
          '',
          'ATTACHED IMAGES — OCR / VISION ANALYSIS ({{imageRefs.count}} image(s) found):',
          '{{vision.analysis}}',
          '',
          'RELATED TICKETS ({{related.count}} found):',
          '{{related.issues}}',
          '',
          'Produce:',
          '## Context',
          'What this ticket is about, including technical details from images and description.',
          '',
          '## Key Technical Terms',
          'Specific code identifiers, API endpoints, class/function names, config keys, error messages, or library names mentioned or implied. These will be used as search queries.',
          '',
          '## Risks & Dependencies',
          'Potential risks or blockers from the ticket and related work.',
        ].join('\n'),
      },
    },
    {
      id: 'adoSearch',
      type: 'ado.deepCodeSearch',
      position: { x: 1160, y: 220 },
      config: {
        adoConfigPath: '{{vars.adoConfigPath}}',
        repoUrl: '{{vars.adoRepoUrl}}',
        searchContext: '{{researchAi.text}}',
        maxResultsPerQuery: 10,
        maxRounds: 2,
        model: 'haiku',
      },
    },
    {
      id: 'synthesize',
      type: 'ai.runPrompt',
      position: { x: 1440, y: 220 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 240000,
        prompt: [
          'You are a senior technical analyst. Combine the Jira research and ADO code search results into a final comprehensive report.',
          '',
          'JIRA RESEARCH:',
          '{{researchAi.text}}',
          '',
          'ADO CODE SEARCH RESULTS ({{adoSearch.count}} files matched across {{adoSearch.rounds}} round(s)):',
          '{{adoSearch.summary}}',
          '',
          'Produce a final research report:',
          '',
          '## Context',
          'What this ticket is about, incorporating all sources.',
          '',
          '## Key Findings',
          'Important details, patterns, and insights from the ticket, related tickets, and matching code.',
          '',
          '## Code References',
          'Relevant code files found in ADO, grouped by repository. For each, explain its relevance to the ticket.',
          '',
          '## Risks & Dependencies',
          'Potential risks, blockers, or dependencies — include code-level concerns found in the search.',
          '',
          '## Next Actions',
          'Concrete recommended next steps, in priority order.',
          '',
          'Be concise. Every claim should be traceable to ticket content, image analysis, related tickets, or code search results.',
        ].join('\n'),
      },
    },
    {
      id: 'write',
      type: 'io.writeFile',
      position: { x: 1720, y: 220 },
      config: {
        path: '{{vars.outputPath}}',
        content: '{{synthesize.text}}',
      },
    },
  ],
  edges: [
    { from: 'seed', to: 'imageRefs' },
    { from: 'seed', to: 'related' },
    { from: 'imageRefs', to: 'vision' },
    { from: 'vision', to: 'researchAi' },
    { from: 'related', to: 'researchAi' },
    { from: 'researchAi', to: 'adoSearch' },
    { from: 'adoSearch', to: 'synthesize' },
    { from: 'researchAi', to: 'synthesize' },
    { from: 'synthesize', to: 'write' },
  ],
  variables: {
    configPath: 'data/Jira/config/jira.env',
    ticket: '',
    model: 'sonnet',
    relatedLimit: '10',
    adoConfigPath: 'data/ADO/config/ado.env',
    adoRepoUrl: '',
    outputPath: 'data/Output/Research/jira-ado-research.md',
  },
};

export const JIRA_RESEARCH_GUIDE_TEMPLATE: WorkflowGraph = {
  id: 'jira-research-guide-template',
  name: 'Jira Research - Guide File',
  description: 'Pulls a Jira ticket, extracts attached images, runs OCR/vision analysis on them, reads a process guide file, then asks AI to produce a research summary with context, risks, dependencies, and next actions. Saves the summary to a file. Requires a guide file path.',
  category: 'Planning & Research',
  nodes: [
    {
      id: 'seed',
      type: 'jira.fetchIssue',
      position: { x: 40, y: 220 },
      config: {
        configPath: '{{vars.configPath}}',
        issueKey: '{{vars.ticket}}',
        fields: 'summary,description,status,priority,issuetype,project,comment,attachment',
      },
    },
    {
      id: 'imageRefs',
      type: 'jira.collectImageRefs',
      position: { x: 320, y: 220 },
      config: {
        issueRaw: '{{seed.raw}}',
      },
    },
    {
      id: 'vision',
      type: 'image.visionExtract',
      position: { x: 600, y: 220 },
      config: {
        model: '{{vars.model}}',
        jiraConfigPath: '{{vars.configPath}}',
        imagePath: '{{imageRefs.refs}}',
        seedSummary: '{{seed.summary}}',
        timeoutMs: 240000,
      },
    },
    {
      id: 'guide',
      type: 'io.readFile',
      position: { x: 880, y: 60 },
      config: {
        path: '{{vars.guide}}',
      },
    },
    {
      id: 'researchAi',
      type: 'ai.runPrompt',
      position: { x: 1160, y: 220 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 240000,
        prompt: [
          'Produce Jira research summary.',
          'Seed: {{seed.key}} - {{seed.summary}}',
          'Description: {{seed.description}}',
          'Follow this process guide exactly:',
          '{{guide.content}}',
          'Image references found: {{imageRefs.count}}',
          'OCR / vision findings: {{vision.analysis}}',
          'Return: context, risks, dependencies, next actions.',
        ].join('\n'),
      },
    },
    {
      id: 'write',
      type: 'io.writeFile',
      position: { x: 1440, y: 220 },
      config: {
        path: '{{vars.outputPath}}',
        content: '{{researchAi.text}}',
      },
    },
  ],
  edges: [
    { from: 'seed', to: 'imageRefs' },
    { from: 'imageRefs', to: 'vision' },
    { from: 'vision', to: 'guide' },
    { from: 'vision', to: 'researchAi' },
    { from: 'guide', to: 'researchAi' },
    { from: 'researchAi', to: 'write' },
  ],
};

export const JIRA_TICKET_GENERATOR_TEMPLATE: WorkflowGraph = {
  id: 'jira-ticket-generator-template',
  name: 'Generate Tickets from Spec',
  description: 'Write a spec (objective, scope, constraints), pull repo code for context, then AI generates implementation-ready Jira tickets and creates them in your project. No PR is created — use this when you just need tickets.',
  category: 'Ticket Generation',
  nodes: [
    {
      id: 'spec',
      type: 'spec.input',
      position: { x: 40, y: 220 },
      config: {
        title: '{{vars.specTitle}}',
        objective: '{{vars.specObjective}}',
        scope: '{{vars.specScope}}',
        constraints: '{{vars.specConstraints}}',
        acceptanceCriteria: '{{vars.specAcceptanceCriteria}}',
        deliverables: '{{vars.specDeliverables}}',
        notes: '{{vars.specNotes}}',
      },
    },
    {
      id: 'repoContext',
      type: 'azuredevops.readRepoContext',
      position: { x: 320, y: 220 },
      config: {
        adoConfigPath: '{{vars.adoConfigPath}}',
        project: '{{vars.azureDevOpsProject}}',
        repository: '{{vars.azureDevOpsRepository}}',
        branch: '{{vars.azureDevOpsBranch}}',
        path: '{{vars.azureDevOpsPath}}',
        maxFiles: '{{vars.azureDevOpsMaxFiles}}',
        maxCharsPerFile: '{{vars.azureDevOpsMaxCharsPerFile}}',
        fileNameFilter: '{{vars.azureDevOpsFileNameFilter}}',
        contentFilter: '{{vars.azureDevOpsContentFilter}}',
      },
    },
    {
      id: 'generateTickets',
      type: 'ai.runPrompt',
      position: { x: 600, y: 220 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 240000,
        prompt: [
          'You are a senior technical PM. Generate Jira tickets from the provided spec and optional codebase context.',
          'If repo context is empty/unavailable, proceed using only the spec.',
          '',
          'Target Workspace/Board: {{vars.board}}',
          'Target Jira Project: {{vars.projectKey}}',
          'Issue Type: {{vars.issueTypeName}}',
          'Ticket Count Guidance: {{config.createIssues.ticketCount}}',
          '',
          'Specification:',
          '{{spec.specText}}',
          '',
          'Azure DevOps Repository Context Summary:',
          '{{repoContext.summary}}',
          '',
          'Return STRICT JSON only in one of these formats:',
          '1) {"tickets":[{...}]}',
          '2) [{...}]',
          '',
          'Each ticket object must contain:',
          '- "summary": short title',
          '- "description": detailed implementation-ready description',
          '- "labels": array of strings (optional)',
          '- "components": array of strings (optional)',
          '- A technical work section that shows the exact code changes needed to be made using the Azure DevOps Repository Context Summary value, if provided. If the change is in a single file, create a code block of the full file change so users can copy/paste the work into the repository. The code changes should be within a dedicated code block, and should not include anything other than the core code so a copy/paste from the ticket is clean and simple.',
          '',
          'IMPORTANT: Code blocks must contain ONLY the final source code. Never use diff format. Never prefix lines with + or - or > symbols. No line annotations or change markers. The code must be directly copied and pasted into a code editor with zero cleanup.',
          '',
          'CRITICAL — NO TRUNCATION: You MUST output the complete, fully functional code for every method, class, and file. NEVER truncate, abbreviate, or omit code. NEVER use placeholder comments like "// ... rest of implementation", "// existing code remains", "// remaining methods", or similar. NEVER say code was "truncated" or reference methods that are not shown. If a file is large, you must still output it in full. Every line of the final file must be present in the code block.',
          '',
          'Tickets should be sequenced logically and split into actionable units.',
        ].join('\n'),
      },
    },
    {
      id: 'createIssues',
      type: 'jira.createIssues',
      position: { x: 880, y: 220 },
      config: {
        configPath: '{{vars.configPath}}',
        projectKey: '{{vars.projectKey}}',
        board: '{{vars.board}}',
        issueTypeName: '{{vars.issueTypeName}}',
        ticketCount: 1,
        tickets: '{{generateTickets.text}}',
        labels: '{{vars.defaultLabels}}',
        components: '{{vars.defaultComponents}}',
        dryRun: '{{vars.dryRun}}',
        targetStatus: '{{vars.targetStatus}}',
      },
    },
  ],
  edges: [
    { from: 'spec', to: 'repoContext' },
    { from: 'repoContext', to: 'generateTickets' },
    { from: 'generateTickets', to: 'createIssues' },
  ],
};

export const JIRA_TICKET_GENERATOR_PR_TEMPLATE: WorkflowGraph = {
  id: 'jira-ticket-generator-pr-template',
  name: 'Generate Tickets + PR from Spec',
  description: 'Write a spec, pull repo code, AI generates tickets, you review and refine in a chat, then tickets are created in Jira, a PR is opened in Azure DevOps, and a comment is posted to the first created ticket with the PR link.',
  category: 'Ticket Generation',
  nodes: [
    {
      id: 'spec',
      type: 'spec.input',
      position: { x: 40, y: 220 },
      config: {
        title: '{{vars.specTitle}}',
        objective: '{{vars.specObjective}}',
        scope: '{{vars.specScope}}',
        constraints: '{{vars.specConstraints}}',
        acceptanceCriteria: '{{vars.specAcceptanceCriteria}}',
        deliverables: '{{vars.specDeliverables}}',
        notes: '{{vars.specNotes}}',
      },
    },
    {
      id: 'repoContext',
      type: 'azuredevops.readRepoContext',
      position: { x: 320, y: 220 },
      config: {
        adoConfigPath: '{{vars.adoConfigPath}}',
        project: '{{vars.azureDevOpsProject}}',
        repository: '{{vars.azureDevOpsRepository}}',
        branch: '{{vars.azureDevOpsBranch}}',
        path: '{{vars.azureDevOpsPath}}',
        maxFiles: '{{vars.azureDevOpsMaxFiles}}',
        maxCharsPerFile: '{{vars.azureDevOpsMaxCharsPerFile}}',
        fileNameFilter: '{{vars.azureDevOpsFileNameFilter}}',
        contentFilter: '{{vars.azureDevOpsContentFilter}}',
      },
    },
    {
      id: 'generateTickets',
      type: 'ai.runPrompt',
      position: { x: 600, y: 220 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 240000,
        prompt: [
          'You are a senior technical PM. Generate Jira tickets from the provided spec and optional codebase context.',
          'If repo context is empty/unavailable, proceed using only the spec.',
          '',
          'Target Workspace/Board: {{vars.board}}',
          'Target Jira Project: {{vars.projectKey}}',
          'Issue Type: {{vars.issueTypeName}}',
          'Ticket Count Guidance: {{config.createIssues.ticketCount}}',
          '',
          'Specification:',
          '{{spec.specText}}',
          '',
          'Azure DevOps Repository Context Summary:',
          '{{repoContext.summary}}',
          '',
          'Return STRICT JSON only in one of these formats:',
          '1) {"tickets":[{...}]}',
          '2) [{...}]',
          '',
          'Each ticket object must contain:',
          '- "summary": short title',
          '- "description": detailed implementation-ready description',
          '- "labels": array of strings (optional)',
          '- "components": array of strings (optional)',
          '- A technical work section that shows the exact code changes needed. If the change is in a single file, create a code block of the full file change so users can copy/paste.',
          '',
          'IMPORTANT: For each file change, use this exact format so the PR automation can extract file paths:',
          '',
          'File: relative/path/from/repo/root.ext',
          '```language',
          'complete file content here',
          '```',
          '',
          'Code blocks must contain ONLY the final source code. Never use diff format. Never prefix lines with + or - or > symbols.',
          '',
          'CRITICAL — NO TRUNCATION: Output the complete, fully functional code for every method, class, and file. NEVER truncate or use placeholder comments.',
          '',
          'Tickets should be sequenced logically and split into actionable units.',
        ].join('\n'),
      },
    },
    {
      id: 'refineChat',
      type: 'ai.interactiveChat',
      position: { x: 880, y: 220 },
      config: {
        model: '{{vars.model}}',
        maxTurns: 10,
      },
    },
    {
      id: 'createIssues',
      type: 'jira.createIssues',
      position: { x: 1100, y: 220 },
      config: {
        configPath: '{{vars.configPath}}',
        projectKey: '{{vars.projectKey}}',
        board: '{{vars.board}}',
        issueTypeName: '{{vars.issueTypeName}}',
        ticketCount: 1,
        tickets: '{{generateTickets.text}}',
        labels: '{{vars.defaultLabels}}',
        components: '{{vars.defaultComponents}}',
        dryRun: '{{vars.dryRun}}',
        targetStatus: '{{vars.targetStatus}}',
      },
    },
    {
      id: 'createPR',
      type: 'azuredevops.createPullRequest',
      position: { x: 1380, y: 220 },
      config: {
        adoConfigPath: '{{vars.adoConfigPath}}',
        project: '{{vars.azureDevOpsProject}}',
        repository: '{{vars.azureDevOpsRepository}}',
        sourceBranch: '{{vars.azureDevOpsBranch}}',
        ticketKey: '{{createIssues.created.0.key}}',
        ticketSummary: '{{createIssues.created.0.summary}}',
        ticketDescription: '{{createIssues.created.0.description}}',
        jiraConfigPath: '{{vars.configPath}}',
        dryRun: '{{vars.dryRunPR}}',
      },
    },
    {
      id: 'addComment',
      type: 'jira.addComment',
      position: { x: 1660, y: 220 },
      config: {
        configPath: '{{vars.configPath}}',
        issueKey: '{{createIssues.created.0.key}}',
        comment: [
          '**Pull Request Created**',
          '',
          'Branch: {{createPR.branchName}}',
          'Files changed: {{createPR.filesChanged}}',
          'PR: {{createPR.prUrl}}',
        ].join('\n'),
      },
    },
  ],
  edges: [
    { from: 'spec', to: 'repoContext' },
    { from: 'repoContext', to: 'generateTickets' },
    { from: 'generateTickets', to: 'refineChat' },
    { from: 'refineChat', to: 'createIssues' },
    { from: 'createIssues', to: 'createPR' },
    { from: 'createPR', to: 'addComment' },
  ],
};

export const JIRA_TICKET_TO_CODE_TEMPLATE: WorkflowGraph = {
  id: 'jira-ticket-to-code-template',
  name: 'Ticket to Code + PR',
  description: 'Pull an existing Jira ticket, pull repo code for context, AI generates implementation code, you review and refine, a PR is opened in Azure DevOps, and a comment is posted back to the original ticket with a code summary and PR link. No child tickets are created — work stays on the original ticket.',
  category: 'End-to-End',
  nodes: [
    {
      id: 'seed',
      type: 'jira.fetchIssue',
      position: { x: 40, y: 220 },
      config: {
        configPath: '{{vars.configPath}}',
        issueKey: '{{vars.ticket}}',
        fields: 'summary,description,status,priority,issuetype,project,comment,attachment',
      },
    },
    {
      id: 'repoContext',
      type: 'azuredevops.readRepoContext',
      position: { x: 320, y: 220 },
      config: {
        adoConfigPath: '{{vars.adoConfigPath}}',
        project: '{{vars.azureDevOpsProject}}',
        repository: '{{vars.azureDevOpsRepository}}',
        branch: '{{vars.azureDevOpsBranch}}',
        path: '{{vars.azureDevOpsPath}}',
        maxFiles: '{{vars.azureDevOpsMaxFiles}}',
        maxCharsPerFile: '{{vars.azureDevOpsMaxCharsPerFile}}',
        fileNameFilter: '{{vars.azureDevOpsFileNameFilter}}',
        contentFilter: '{{vars.azureDevOpsContentFilter}}',
      },
    },
    {
      id: 'generateCode',
      type: 'ai.runPrompt',
      position: { x: 600, y: 220 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 240000,
        prompt: [
          'You are a senior software engineer. Implement EXACTLY what the REQUIREMENTS section asks for.',
          '',
          'CRITICAL RULES:',
          '- Read the REQUIREMENTS section carefully. That is the task to implement.',
          '- The CODEBASE CONTEXT section shows existing code for reference only.',
          '- Do NOT fix bugs, refactor, or change anything in the codebase that is not explicitly requested by the requirements.',
          '- Your implementation must directly address the requirements — nothing more, nothing less.',
          '- ONLY use file paths that are explicitly listed in the CODEBASE CONTEXT. NEVER invent or guess file paths.',
          '',
          '{{_upstream}}',
          '',
          'Output your implementation in this format:',
          '',
          '## Summary',
          'A brief description of what was implemented and why.',
          '',
          '## Changes',
          'For each file changed, use this EXACT format so the PR automation can extract file paths:',
          '',
          'File: relative/path/from/repo/root.ext',
          '```language',
          'complete file content here',
          '```',
          '',
          'Code blocks must contain ONLY the final source code. Never use diff format. Never prefix lines with + or - or > symbols.',
          '',
          'CRITICAL — NO TRUNCATION: Output the complete, fully functional code for every method, class, and file. NEVER truncate or use placeholder comments.',
        ].join('\n'),
      },
    },
    {
      id: 'refineChat',
      type: 'ai.interactiveChat',
      position: { x: 880, y: 220 },
      config: {
        model: '{{vars.model}}',
        maxTurns: 10,
      },
    },
    {
      id: 'createPR',
      type: 'azuredevops.createPullRequest',
      position: { x: 1160, y: 220 },
      config: {
        adoConfigPath: '{{vars.adoConfigPath}}',
        project: '{{vars.azureDevOpsProject}}',
        repository: '{{vars.azureDevOpsRepository}}',
        sourceBranch: '{{vars.azureDevOpsBranch}}',
        ticketKey: '{{seed.key}}',
        ticketSummary: '{{seed.summary}}',
        ticketDescription: '{{generateCode.text}}',
        jiraConfigPath: '{{vars.configPath}}',
        dryRun: '{{vars.dryRunPR}}',
      },
    },
    {
      id: 'addComment',
      type: 'jira.addComment',
      position: { x: 1440, y: 220 },
      config: {
        configPath: '{{vars.configPath}}',
        issueKey: '{{seed.key}}',
        comment: [
          '**Automated Implementation**',
          '',
          'Branch: {{createPR.branchName}}',
          'Files changed: {{createPR.filesChanged}}',
          'PR: {{createPR.prUrl}}',
          '',
          '---',
          '',
          '{{generateCode.text}}',
        ].join('\n'),
      },
    },
  ],
  edges: [
    { from: 'seed', to: 'repoContext' },
    { from: 'repoContext', to: 'generateCode' },
    { from: 'generateCode', to: 'refineChat' },
    { from: 'refineChat', to: 'createPR' },
    { from: 'createPR', to: 'addComment' },
  ],
};

export const JIRA_SPEC_TO_CODE_TEMPLATE: WorkflowGraph = {
  id: 'jira-spec-to-code-template',
  name: 'Spec to Code Tickets + PR',
  description: 'Write a spec from scratch, pull repo code for context, AI generates implementation-ready Jira tickets with full code in the descriptions, you review and refine, tickets are created in Jira, a PR is opened in Azure DevOps, and a comment is posted to the first ticket with the PR link.',
  category: 'End-to-End',
  nodes: [
    {
      id: 'spec',
      type: 'spec.input',
      position: { x: 40, y: 220 },
      config: {
        title: '{{vars.specTitle}}',
        objective: '{{vars.specObjective}}',
        scope: '{{vars.specScope}}',
        constraints: '{{vars.specConstraints}}',
        acceptanceCriteria: '{{vars.specAcceptanceCriteria}}',
        deliverables: '{{vars.specDeliverables}}',
        notes: '{{vars.specNotes}}',
      },
    },
    {
      id: 'repoContext',
      type: 'azuredevops.readRepoContext',
      position: { x: 320, y: 220 },
      config: {
        adoConfigPath: '{{vars.adoConfigPath}}',
        project: '{{vars.azureDevOpsProject}}',
        repository: '{{vars.azureDevOpsRepository}}',
        branch: '{{vars.azureDevOpsBranch}}',
        path: '{{vars.azureDevOpsPath}}',
        maxFiles: '{{vars.azureDevOpsMaxFiles}}',
        maxCharsPerFile: '{{vars.azureDevOpsMaxCharsPerFile}}',
        fileNameFilter: '{{vars.azureDevOpsFileNameFilter}}',
        contentFilter: '{{vars.azureDevOpsContentFilter}}',
      },
    },
    {
      id: 'generateTickets',
      type: 'ai.runPrompt',
      position: { x: 600, y: 220 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 240000,
        prompt: [
          'You are a senior software engineer and technical PM. Generate Jira tickets that implement EXACTLY what the SPECIFICATION asks for.',
          '',
          'CRITICAL RULES:',
          '- Read the SPECIFICATION section carefully. That is the task to implement.',
          '- The CODEBASE CONTEXT section shows existing code for reference only.',
          '- Do NOT fix bugs, refactor, or change anything in the codebase that is not explicitly requested by the specification.',
          '- Your tickets must directly address the specification — nothing more, nothing less.',
          '- ONLY use file paths that are explicitly listed in the CODEBASE CONTEXT. NEVER invent or guess file paths.',
          '',
          'Target Workspace/Board: {{vars.board}}',
          'Target Jira Project: {{vars.projectKey}}',
          'Issue Type: {{vars.issueTypeName}}',
          '',
          'SPECIFICATION:',
          '{{spec.specText}}',
          '',
          'CODEBASE CONTEXT:',
          '{{repoContext.summary}}',
          '',
          'Return STRICT JSON only in one of these formats:',
          '1) {"tickets":[{...}]}',
          '2) [{...}]',
          '',
          'Each ticket object must contain:',
          '- "summary": short title that reflects the requirement',
          '- "description": detailed implementation-ready description including the full code',
          '- "labels": array of strings (optional)',
          '- "components": array of strings (optional)',
          '',
          'The description MUST include the complete code implementation. For each file change, use this EXACT format so the PR automation can extract file paths:',
          '',
          'File: relative/path/from/repo/root.ext',
          '```language',
          'complete file content here',
          '```',
          '',
          'Code blocks must contain ONLY the final source code. Never use diff format. Never prefix lines with + or - or > symbols.',
          '',
          'CRITICAL — NO TRUNCATION: Output the complete, fully functional code for every method, class, and file. NEVER truncate or use placeholder comments.',
          '',
          'Tickets should be sequenced logically and split into actionable units.',
        ].join('\n'),
      },
    },
    {
      id: 'refineChat',
      type: 'ai.interactiveChat',
      position: { x: 880, y: 220 },
      config: {
        model: '{{vars.model}}',
        maxTurns: 10,
      },
    },
    {
      id: 'createIssues',
      type: 'jira.createIssues',
      position: { x: 1100, y: 220 },
      config: {
        configPath: '{{vars.configPath}}',
        projectKey: '{{vars.projectKey}}',
        board: '{{vars.board}}',
        issueTypeName: '{{vars.issueTypeName}}',
        ticketCount: 1,
        tickets: '{{generateTickets.text}}',
        labels: '{{vars.defaultLabels}}',
        components: '{{vars.defaultComponents}}',
        dryRun: '{{vars.dryRun}}',
        targetStatus: '{{vars.targetStatus}}',
      },
    },
    {
      id: 'createPR',
      type: 'azuredevops.createPullRequest',
      position: { x: 1380, y: 220 },
      config: {
        adoConfigPath: '{{vars.adoConfigPath}}',
        project: '{{vars.azureDevOpsProject}}',
        repository: '{{vars.azureDevOpsRepository}}',
        sourceBranch: '{{vars.azureDevOpsBranch}}',
        ticketKey: '{{createIssues.created.0.key}}',
        ticketSummary: '{{createIssues.created.0.summary}}',
        ticketDescription: '{{createIssues.created.0.description}}',
        jiraConfigPath: '{{vars.configPath}}',
        dryRun: '{{vars.dryRunPR}}',
      },
    },
    {
      id: 'addComment',
      type: 'jira.addComment',
      position: { x: 1660, y: 220 },
      config: {
        configPath: '{{vars.configPath}}',
        issueKey: '{{createIssues.created.0.key}}',
        comment: [
          '**Pull Request Created**',
          '',
          'Branch: {{createPR.branchName}}',
          'Files changed: {{createPR.filesChanged}}',
          'PR: {{createPR.prUrl}}',
        ].join('\n'),
      },
    },
  ],
  edges: [
    { from: 'spec', to: 'repoContext' },
    { from: 'repoContext', to: 'generateTickets' },
    { from: 'generateTickets', to: 'refineChat' },
    { from: 'refineChat', to: 'createIssues' },
    { from: 'createIssues', to: 'createPR' },
    { from: 'createPR', to: 'addComment' },
  ],
};

export const JIRA_REVIEW_REFINE_TEMPLATE: WorkflowGraph = {
  id: 'jira-review-refine-template',
  name: 'Review & Refine Existing Ticket',
  description: 'Pulls a Jira ticket, extracts and analyzes attached images via OCR/vision, uses AI to analyze its contents and suggest targeted search queries, searches Jira for additional context, synthesizes all findings (including image insights), lets you review and refine the result, then updates the original ticket with the improved description.',
  category: 'Planning & Research',
  nodes: [
    {
      id: 'seed',
      type: 'jira.fetchIssue',
      position: { x: 40, y: 220 },
      config: {
        configPath: '{{vars.configPath}}',
        issueKey: '{{vars.ticket}}',
        fields: 'summary,description,status,priority,issuetype,project,comment,attachment',
      },
    },
    {
      id: 'imageRefs',
      type: 'jira.collectImageRefs',
      position: { x: 320, y: 60 },
      config: {
        issueRaw: '{{seed.raw}}',
      },
    },
    {
      id: 'vision',
      type: 'image.visionExtract',
      position: { x: 600, y: 60 },
      config: {
        model: '{{vars.model}}',
        jiraConfigPath: '{{vars.configPath}}',
        imagePath: '{{imageRefs.refs}}',
        seedSummary: '{{seed.summary}}',
        timeoutMs: 240000,
      },
    },
    {
      id: 'analyzeAi',
      type: 'ai.runPrompt',
      position: { x: 320, y: 220 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 240000,
        prompt: [
          'You are a senior technical analyst reviewing a Jira ticket. Your job is to:',
          '1. Analyze the ticket contents and identify gaps, ambiguities, or areas that need more detail.',
          '2. Output a JQL search query that will find the most relevant related tickets in this project.',
          '3. Provide an initial analysis of the ticket.',
          '',
          'TICKET:',
          'Key: {{seed.key}}',
          'Summary: {{seed.summary}}',
          'Description:',
          '{{seed.description}}',
          '',
          'Output your response in this exact format:',
          '',
          'SEARCH_JQL: project = "{{seed.raw.fields.project.key}}" AND text ~ "your search terms here" AND key != "{{seed.key}}" ORDER BY updated DESC',
          '',
          'INITIAL_ANALYSIS:',
          '(your analysis of the ticket — what it covers, what is missing, what needs clarification)',
        ].join('\n'),
      },
    },
    {
      id: 'contextSearch',
      type: 'jira.searchJql',
      position: { x: 320, y: 380 },
      config: {
        configPath: '{{vars.configPath}}',
        jql: 'project = "{{seed.raw.fields.project.key}}" AND text ~ "{{seed.summary}}" AND key != "{{seed.key}}" ORDER BY updated DESC',
        maxResults: '{{vars.relatedLimit}}',
        fields: 'summary,description,status,priority,issuetype',
      },
    },
    {
      id: 'synthesizeAi',
      type: 'ai.runPrompt',
      position: { x: 880, y: 220 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 240000,
        prompt: [
          'You are a senior technical analyst. Synthesize all the information below into a comprehensive, refined ticket description.',
          '',
          'ORIGINAL TICKET:',
          'Key: {{seed.key}}',
          'Summary: {{seed.summary}}',
          'Description:',
          '{{seed.description}}',
          '',
          'AI ANALYSIS:',
          '{{analyzeAi.text}}',
          '',
          'ATTACHED IMAGES — OCR / VISION ANALYSIS ({{imageRefs.count}} image(s) found):',
          'The following is extracted text and visual analysis from images attached to this ticket.',
          'If images were found, you MUST incorporate their content (OCR text, UI elements, diagrams, error messages, etc.) into your refined description.',
          '',
          '{{vision.analysis}}',
          '',
          'RELATED TICKETS ({{contextSearch.count}} found):',
          '{{contextSearch.issues}}',
          '',
          'Write an improved, thorough ticket description in markdown that:',
          '- Preserves the original intent and requirements',
          '- Fills in gaps identified in the analysis',
          '- If images contained useful information (screenshots, diagrams, error messages, UI mockups), weave those details into the relevant sections of the description — do not just list them in a separate section',
          '- Incorporates relevant context from related tickets',
          '- Adds acceptance criteria if missing',
          '- Adds technical considerations or dependencies found in related work',
          '- Uses clear structure with headers, bullet points, and sections',
          '',
          'Output ONLY the improved description text — no preamble or explanation.',
        ].join('\n'),
      },
    },
    {
      id: 'refineChat',
      type: 'ai.interactiveChat',
      position: { x: 1160, y: 220 },
      config: {
        model: '{{vars.model}}',
        maxTurns: 10,
      },
    },
    {
      id: 'updateTicket',
      type: 'jira.updateIssue',
      position: { x: 1440, y: 220 },
      config: {
        configPath: '{{vars.configPath}}',
        issueKey: '{{seed.key}}',
        mode: '{{vars.updateMode}}',
        description: '{{synthesizeAi.text}}',
        imageAttachments: '{{imageRefs.attachments}}',
        dryRun: '{{vars.dryRun}}',
      },
    },
  ],
  edges: [
    { from: 'seed', to: 'imageRefs' },
    { from: 'seed', to: 'analyzeAi' },
    { from: 'seed', to: 'contextSearch' },
    { from: 'imageRefs', to: 'vision' },
    { from: 'vision', to: 'synthesizeAi' },
    { from: 'analyzeAi', to: 'synthesizeAi' },
    { from: 'contextSearch', to: 'synthesizeAi' },
    { from: 'synthesizeAi', to: 'refineChat' },
    { from: 'refineChat', to: 'updateTicket' },
  ],
};

export const DEEP_RESEARCH_TEMPLATE: WorkflowGraph = {
  id: 'deep-research-template',
  name: 'Deep Research',
  description: 'Reads a Jira ticket, follows external links, then runs AI-planned searches across ADO code, Confluence, and Jira — with automatic retry on empty results. Produces a concise research summary answering the ticket\'s questions (impact, inventory of impacted systems, owning teams) and posts it back as a comment.',
  category: 'Planning & Research',
  nodes: [
    // ── Stage 1: Gather the ticket ──────────────────────────────────
    {
      id: 'seed',
      type: 'jira.fetchIssue',
      position: { x: 40, y: 220 },
      config: {
        configPath: '{{vars.configPath}}',
        issueKey: '{{vars.ticket}}',
        fields: 'summary,description,status,priority,issuetype,project,comment,attachment',
      },
    },

    // ── Stage 2: Follow external links from the ticket ──────────────
    {
      id: 'webFetch',
      type: 'web.fetchUrl',
      position: { x: 320, y: 220 },
      config: {
        urls: '{{seed.urls}}\n{{vars.externalUrls}}',
        timeoutMs: 30000,
      },
    },

    // ── Stage 3: AI plans the search strategy ───────────────────────
    {
      id: 'planSearch',
      type: 'ai.runPrompt',
      position: { x: 600, y: 220 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 240000,
        prompt: [
          'You are a senior research analyst. Analyze this ticket and external web content to produce a search strategy.',
          '',
          'TICKET:',
          '{{seed.key}} — {{seed.summary}}',
          '{{seed.description}}',
          '',
          'EXTERNAL WEB CONTENT (from links in the ticket):',
          '{{webFetch.content}}',
          '',
          'YOUR TASK:',
          '1. Summarize the core change/deprecation/issue described in the ticket and web content.',
          '2. Identify specific technical identifiers to search for: API names, library names, NuGet/npm packages, SDK classes, config keys, Terraform resource types, endpoint URLs, etc.',
          '3. Produce THREE sections:',
          '',
          '## Change Summary',
          'A 2-3 sentence description of what is changing and why it matters.',
          '',
          '## ADO Code Search Queries',
          'Return 1-3 search queries (one per line) optimized for Azure DevOps code search.',
          'Use specific identifiers like class names, method calls, import statements, package names.',
          'Example: "Microsoft.Graph" OR "GraphServiceClient"',
          '',
          '## Confluence Search Queries',
          'Return 1-3 search queries (one per line) optimized for Confluence text search.',
          'Focus on architecture docs, runbooks, integration docs, team pages.',
          'Example: Microsoft Graph integration architecture',
          '',
          '## Jira Search JQL',
          'Return a JQL query to find related Jira tickets.',
          'Example: text ~ "Microsoft Graph" ORDER BY updated DESC',
          '',
          'Be specific and technical. The goal is to find every system that might be impacted.',
        ].join('\n'),
      },
    },

    // ── Stage 4: Parallel searches (ADO, Confluence, Jira) ──────────
    {
      id: 'adoSearch',
      type: 'ado.deepCodeSearch',
      position: { x: 880, y: 60 },
      config: {
        adoConfigPath: '{{vars.adoConfigPath}}',
        repoUrl: '{{vars.adoRepoUrl}}',
        searchContext: '{{planSearch.text}}',
        maxResultsPerQuery: 10,
        maxRounds: 2,
        model: 'haiku',
      },
    },
    {
      id: 'confluenceSearch',
      type: 'confluence.search',
      position: { x: 880, y: 220 },
      config: {
        configPath: '{{vars.configPath}}',
        query: '{{vars.confluenceSearchQuery}}',
        spaceKey: '{{vars.confluenceSpaceKey}}',
        maxResults: 15,
        maxRetries: 2,
        searchContext: '{{planSearch.text}}',
        model: 'haiku',
      },
    },
    {
      id: 'jiraSearch',
      type: 'jira.searchJql',
      position: { x: 880, y: 380 },
      config: {
        configPath: '{{vars.configPath}}',
        jql: '{{vars.jiraSearchJql}}',
        maxResults: 15,
        fields: 'summary,description,status,priority,issuetype,project,assignee,labels',
        searchContext: '{{planSearch.text}}',
        model: 'haiku',
      },
    },

    // ── Stage 5: AI synthesizes all findings ────────────────────────
    {
      id: 'synthesize',
      type: 'ai.runPrompt',
      position: { x: 1160, y: 220 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 240000,
        prompt: [
          'You are a senior research analyst completing a deep research task. Compile your findings into a clear, concise report.',
          '',
          'ORIGINAL RESEARCH REQUEST:',
          '{{seed.key}} — {{seed.summary}}',
          '{{seed.description}}',
          '',
          'CHANGE ANALYSIS (from AI planning):',
          '{{planSearch.text}}',
          '',
          'AZURE DEVOPS CODE SEARCH RESULTS:',
          '{{adoSearch.summary}}',
          'Queries tried: {{adoSearch.queries}}',
          '',
          'CONFLUENCE SEARCH RESULTS:',
          '{{confluenceSearch.summary}}',
          'Queries tried: {{confluenceSearch.queries}}',
          '',
          'JIRA SEARCH RESULTS (related tickets):',
          '{{jiraSearch.count}} related tickets found.',
          '{{jiraSearch.issues}}',
          '',
          'INSTRUCTIONS:',
          'Write a research report answering the ticket\'s questions. Use ONLY what the search results support — do not speculate. Structure your response as:',
          '',
          '## Change Summary',
          'What is changing and why.',
          '',
          '## Impact Assessment',
          'What impact this will have to our systems. State "No impact found" if searches returned nothing.',
          '',
          '## Impacted Systems Inventory',
          'A numbered list of impacted systems with:',
          '- Repository name (this is an ADO Git repository — label it as such)',
          '- ADO Project name (if available from the search results)',
          '- Specific files — PRESERVE the markdown links from the search results as-is (e.g. [/path/file.json](https://...))',
          '- Nature of the dependency',
          '- Severity (high/medium/low)',
          'IMPORTANT: When referencing repositories, files, or projects from the ADO search results, always clarify what type of resource it is (ADO Repository, ADO Project, file path). Preserve any markdown links from the search results so the reader can click through to the source.',
          'If no matches found, state that clearly.',
          '',
          '## Owning Teams',
          'For each impacted system, identify the owning team (from Jira assignees, repo names, or Confluence spaces).',
          '',
          '## Recommended Next Steps',
          'Concrete actions to take, in priority order.',
          '',
          '## Search Coverage',
          'What was searched and what wasn\'t — so the reader knows the research boundaries.',
          '',
          'Be concise. Every claim must trace back to a search result.',
        ].join('\n'),
      },
    },

    // ── Stage 6: Interactive review ─────────────────────────────────
    {
      id: 'refineChat',
      type: 'ai.interactiveChat',
      position: { x: 1440, y: 220 },
      config: {
        model: '{{vars.model}}',
        maxTurns: 15,
      },
    },

    // ── Stage 7: Post back to the ticket ────────────────────────────
    {
      id: 'addComment',
      type: 'jira.addComment',
      position: { x: 1720, y: 220 },
      config: {
        configPath: '{{vars.configPath}}',
        issueKey: '{{seed.key}}',
        comment: [
          '**Deep Research Report**',
          '',
          '{{refineChat.text}}',
          '',
          '---',
          '_Generated by Workflow Studio — Deep Research template_',
        ].join('\n'),
      },
    },
  ],
  edges: [
    { from: 'seed', to: 'webFetch' },
    { from: 'webFetch', to: 'planSearch' },
    // Parallel searches — all depend on planSearch, independent of each other
    { from: 'planSearch', to: 'adoSearch' },
    { from: 'planSearch', to: 'confluenceSearch' },
    { from: 'planSearch', to: 'jiraSearch' },
    // Synthesis depends on all three searches
    { from: 'adoSearch', to: 'synthesize' },
    { from: 'confluenceSearch', to: 'synthesize' },
    { from: 'jiraSearch', to: 'synthesize' },
    { from: 'synthesize', to: 'refineChat' },
    { from: 'refineChat', to: 'addComment' },
  ],
  variables: {
    configPath: 'data/Jira/config/jira.env',
    ticket: '',
    model: 'sonnet',
    externalUrls: '',
    adoConfigPath: 'data/ADO/config/ado.env',
    adoRepoUrl: '',
    confluenceSearchQuery: '',
    confluenceSpaceKey: '',
    jiraSearchJql: '',
    outputPath: 'data/Output/Deep-Research/research-report.md',
  },
};

export const INCIDENT_RESPONSE_TEMPLATE: WorkflowGraph = {
  id: 'incident-response-template',
  name: 'Incident Response',
  description: 'Reads a Jira incident ticket, searches ADO code and Confluence for related systems, uses AI to assess impact and recommend remediation steps, then posts a structured incident report back to the ticket and notifies a Slack channel.',
  category: 'Incident Management',
  nodes: [
    {
      id: 'incident',
      type: 'jira.fetchIssue',
      position: { x: 40, y: 220 },
      config: {
        configPath: '{{vars.configPath}}',
        issueKey: '{{vars.ticket}}',
        fields: 'summary,description,status,priority,issuetype,project,comment,attachment,labels',
      },
    },
    {
      id: 'adoSearch',
      type: 'ado.deepCodeSearch',
      position: { x: 320, y: 60 },
      config: {
        adoConfigPath: '{{vars.adoConfigPath}}',
        repoUrl: '{{vars.adoRepoUrl}}',
        searchContext: '{{incident.summary}}\n{{incident.description}}',
        maxResultsPerQuery: 10,
        maxRounds: 2,
        model: 'haiku',
      },
    },
    {
      id: 'confluenceSearch',
      type: 'confluence.search',
      position: { x: 320, y: 380 },
      config: {
        configPath: '{{vars.configPath}}',
        query: '{{incident.summary}}',
        spaceKey: '{{vars.confluenceSpaceKey}}',
        maxResults: 10,
        maxRetries: 2,
        searchContext: '{{incident.summary}}\n{{incident.description}}',
        model: 'haiku',
      },
    },
    {
      id: 'assessAi',
      type: 'ai.runPrompt',
      position: { x: 600, y: 220 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 240000,
        prompt: [
          'You are an incident response analyst. Assess the following incident and produce a structured incident report.',
          '',
          'INCIDENT:',
          '{{incident.key}} — {{incident.summary}}',
          'Priority: {{incident.raw.fields.priority.name}}',
          'Description: {{incident.description}}',
          '',
          'CODE SEARCH RESULTS (potential impacted systems):',
          '{{adoSearch.summary}}',
          '',
          'CONFLUENCE DOCS (runbooks, architecture docs):',
          '{{confluenceSearch.summary}}',
          '',
          'Produce a structured report with these sections:',
          '',
          '## Incident Summary',
          'Brief description of the incident.',
          '',
          '## Severity Assessment',
          'Severity level (P1-P4) with justification based on the evidence.',
          '',
          '## Impacted Systems',
          'Numbered list of affected systems/services with evidence from code search.',
          '',
          '## Root Cause Analysis',
          'Probable root cause based on available evidence. State clearly if this is speculative.',
          '',
          '## Remediation Steps',
          'Numbered priority-ordered steps to resolve the incident.',
          '',
          '## Runbook References',
          'Relevant Confluence pages for responders (from the search results).',
          '',
          '## Communication Plan',
          'Who needs to be notified and when.',
        ].join('\n'),
      },
    },
    {
      id: 'refineChat',
      type: 'ai.interactiveChat',
      position: { x: 880, y: 220 },
      config: {
        model: '{{vars.model}}',
        maxTurns: 10,
      },
    },
    {
      id: 'addComment',
      type: 'jira.addComment',
      position: { x: 1160, y: 60 },
      config: {
        configPath: '{{vars.configPath}}',
        issueKey: '{{incident.key}}',
        comment: [
          '**Incident Response Report**',
          '',
          '{{refineChat.text}}',
          '',
          '---',
          '_Generated by Workflow Studio — Incident Response template_',
        ].join('\n'),
      },
    },
    {
      id: 'slackNotify',
      type: 'slack.sendMessage',
      position: { x: 1160, y: 380 },
      config: {
        webhookUrl: '{{vars.slackWebhookUrl}}',
        message: [
          ':rotating_light: *Incident Report Posted*',
          '',
          '*{{incident.key}}* — {{incident.summary}}',
          'Priority: {{incident.raw.fields.priority.name}}',
          '',
          'A structured incident response report has been added to the ticket.',
          'View: {{vars.jiraBaseUrl}}/browse/{{incident.key}}',
        ].join('\n'),
        username: 'Workflow Studio',
        iconEmoji: ':fire_engine:',
      },
    },
  ],
  edges: [
    { from: 'incident', to: 'adoSearch' },
    { from: 'incident', to: 'confluenceSearch' },
    { from: 'adoSearch', to: 'assessAi' },
    { from: 'confluenceSearch', to: 'assessAi' },
    { from: 'assessAi', to: 'refineChat' },
    { from: 'refineChat', to: 'addComment' },
    { from: 'refineChat', to: 'slackNotify' },
  ],
  variables: {
    configPath: 'data/Jira/config/jira.env',
    ticket: '',
    model: 'sonnet',
    adoConfigPath: 'data/ADO/config/ado.env',
    adoRepoUrl: '',
    confluenceSpaceKey: '',
    slackWebhookUrl: '',
    jiraBaseUrl: '',
  },
};

export const SPRINT_REPORT_TEMPLATE: WorkflowGraph = {
  id: 'sprint-report-template',
  name: 'Sprint Report',
  description: 'Searches Jira for tickets completed in the current sprint, uses AI to analyze velocity, blockers, and patterns, generates a sprint summary report, and optionally posts it to Slack.',
  category: 'Reporting',
  nodes: [
    {
      id: 'completedTickets',
      type: 'jira.searchJql',
      position: { x: 40, y: 60 },
      config: {
        configPath: '{{vars.configPath}}',
        jql: '{{vars.sprintJql}}',
        maxResults: 50,
        fields: 'summary,description,status,priority,issuetype,project,assignee,labels,story_points,timespent',
      },
    },
    {
      id: 'inProgressTickets',
      type: 'jira.searchJql',
      position: { x: 40, y: 380 },
      config: {
        configPath: '{{vars.configPath}}',
        jql: '{{vars.inProgressJql}}',
        maxResults: 30,
        fields: 'summary,description,status,priority,issuetype,project,assignee,labels',
      },
    },
    {
      id: 'analyzeAi',
      type: 'ai.runPrompt',
      position: { x: 320, y: 220 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 240000,
        prompt: [
          'You are a scrum master generating a sprint report. Analyze the following ticket data and produce a comprehensive sprint summary.',
          '',
          'COMPLETED TICKETS ({{completedTickets.count}}):',
          '{{completedTickets.issues}}',
          '',
          'IN PROGRESS / CARRY-OVER TICKETS ({{inProgressTickets.count}}):',
          '{{inProgressTickets.issues}}',
          '',
          'Generate a sprint report with these sections:',
          '',
          '## Sprint Summary',
          'Overview of what was accomplished vs. planned.',
          '',
          '## Completed Work',
          'Categorized list of completed items grouped by type (feature, bug fix, tech debt, etc.).',
          '',
          '## Velocity & Metrics',
          '- Tickets completed vs. carried over',
          '- Completion rate percentage',
          '- Priority distribution',
          '',
          '## Carry-Over Items',
          'Work that didn\'t finish this sprint with brief reason assessment.',
          '',
          '## Patterns & Observations',
          'Trends, blockers, or recurring themes the team should discuss.',
          '',
          '## Recommendations',
          'Actionable suggestions for the next sprint.',
        ].join('\n'),
      },
    },
    {
      id: 'refineChat',
      type: 'ai.interactiveChat',
      position: { x: 600, y: 220 },
      config: {
        model: '{{vars.model}}',
        maxTurns: 10,
      },
    },
    {
      id: 'writeReport',
      type: 'io.writeFile',
      position: { x: 880, y: 60 },
      config: {
        path: '{{vars.outputPath}}',
        content: '{{refineChat.text}}',
      },
    },
    {
      id: 'slackPost',
      type: 'slack.sendMessage',
      position: { x: 880, y: 380 },
      config: {
        webhookUrl: '{{vars.slackWebhookUrl}}',
        message: [
          ':bar_chart: *Sprint Report*',
          '',
          '{{refineChat.text}}',
        ].join('\n'),
        username: 'Sprint Bot',
        iconEmoji: ':chart_with_upwards_trend:',
      },
    },
  ],
  edges: [
    { from: 'completedTickets', to: 'analyzeAi' },
    { from: 'inProgressTickets', to: 'analyzeAi' },
    { from: 'analyzeAi', to: 'refineChat' },
    { from: 'refineChat', to: 'writeReport' },
    { from: 'refineChat', to: 'slackPost' },
  ],
  variables: {
    configPath: 'data/Jira/config/jira.env',
    sprintJql: 'project = "PROJ" AND sprint in openSprints() AND status = Done ORDER BY priority DESC',
    inProgressJql: 'project = "PROJ" AND sprint in openSprints() AND status != Done ORDER BY priority DESC',
    model: 'sonnet',
    outputPath: 'data/Output/Sprint-Reports/sprint-report.md',
    slackWebhookUrl: '',
  },
};

export const CHANGE_IMPACT_TEMPLATE: WorkflowGraph = {
  id: 'change-impact-template',
  name: 'Change Impact Analysis',
  description: 'Given a description of a planned change, searches across ADO code, Confluence docs, and Jira to identify every system that would be affected. Produces a risk-scored impact matrix and notifies stakeholders.',
  category: 'Planning & Research',
  nodes: [
    {
      id: 'changeSpec',
      type: 'spec.input',
      position: { x: 40, y: 220 },
      config: {
        title: '{{vars.changeTitle}}',
        objective: '{{vars.changeDescription}}',
        scope: '{{vars.affectedAreas}}',
        constraints: '{{vars.timeline}}',
        acceptanceCriteria: '',
        deliverables: '',
        notes: '{{vars.additionalContext}}',
      },
    },
    {
      id: 'planSearch',
      type: 'ai.runPrompt',
      position: { x: 320, y: 220 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 240000,
        prompt: [
          'You are a change impact analyst. Given the following planned change, produce search queries to find all affected systems.',
          '',
          'PLANNED CHANGE:',
          '{{changeSpec.specText}}',
          '',
          'Generate targeted search queries for each platform:',
          '',
          '## ADO Code Search Queries',
          'Specific code patterns, imports, API calls, config keys that would be affected.',
          '',
          '## Confluence Search Queries',
          'Architecture docs, runbooks, integration guides.',
          '',
          '## Jira Search JQL',
          'Related tickets, previous changes, known issues.',
          '',
          'Be exhaustive — search for direct and indirect dependencies.',
        ].join('\n'),
      },
    },
    {
      id: 'adoSearch',
      type: 'ado.deepCodeSearch',
      position: { x: 600, y: 60 },
      config: {
        adoConfigPath: '{{vars.adoConfigPath}}',
        repoUrl: '{{vars.adoRepoUrl}}',
        searchContext: '{{planSearch.text}}',
        maxResultsPerQuery: 10,
        maxRounds: 2,
        model: 'haiku',
      },
    },
    {
      id: 'confluenceSearch',
      type: 'confluence.search',
      position: { x: 600, y: 220 },
      config: {
        configPath: '{{vars.configPath}}',
        query: '{{vars.confluenceSearchQuery}}',
        spaceKey: '{{vars.confluenceSpaceKey}}',
        maxResults: 15,
        maxRetries: 2,
        searchContext: '{{planSearch.text}}',
        model: 'haiku',
      },
    },
    {
      id: 'jiraSearch',
      type: 'jira.searchJql',
      position: { x: 600, y: 380 },
      config: {
        configPath: '{{vars.configPath}}',
        jql: '{{vars.jiraSearchJql}}',
        maxResults: 20,
        fields: 'summary,description,status,priority,issuetype,project,assignee,labels',
        searchContext: '{{planSearch.text}}',
        model: 'haiku',
      },
    },
    {
      id: 'synthesize',
      type: 'ai.runPrompt',
      position: { x: 880, y: 220 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 240000,
        prompt: [
          'You are a change impact analyst. Compile all findings into a comprehensive impact analysis.',
          '',
          'PLANNED CHANGE:',
          '{{changeSpec.specText}}',
          '',
          'ADO CODE SEARCH RESULTS:',
          '{{adoSearch.summary}}',
          '',
          'CONFLUENCE SEARCH RESULTS:',
          '{{confluenceSearch.summary}}',
          '',
          'RELATED JIRA TICKETS:',
          '{{jiraSearch.issues}}',
          '',
          'Produce an impact analysis with:',
          '',
          '## Change Overview',
          'What is being changed and why.',
          '',
          '## Impact Matrix',
          'Table of impacted systems with:',
          '| System | Repository | Impact Type | Risk Level | Details |',
          '',
          '## Risk Assessment',
          'Overall risk level with justification.',
          '',
          '## Dependency Chain',
          'How the change cascades through systems.',
          '',
          '## Recommended Rollout Plan',
          'Phased approach with rollback points.',
          '',
          '## Stakeholder Notifications',
          'Who needs to know, organized by team.',
          '',
          'Base everything on search evidence. Mark speculation clearly.',
        ].join('\n'),
      },
    },
    {
      id: 'refineChat',
      type: 'ai.interactiveChat',
      position: { x: 1160, y: 220 },
      config: {
        model: '{{vars.model}}',
        maxTurns: 10,
      },
    },
    {
      id: 'writeReport',
      type: 'io.writeFile',
      position: { x: 1440, y: 60 },
      config: {
        path: '{{vars.outputPath}}',
        content: '{{refineChat.text}}',
      },
    },
    {
      id: 'slackNotify',
      type: 'slack.sendMessage',
      position: { x: 1440, y: 380 },
      config: {
        webhookUrl: '{{vars.slackWebhookUrl}}',
        message: [
          ':mag: *Change Impact Analysis Complete*',
          '',
          '*{{vars.changeTitle}}*',
          '',
          'A full impact analysis has been generated.',
          'Report saved to: `{{vars.outputPath}}`',
        ].join('\n'),
        username: 'Impact Analyzer',
        iconEmoji: ':shield:',
      },
    },
  ],
  edges: [
    { from: 'changeSpec', to: 'planSearch' },
    { from: 'planSearch', to: 'adoSearch' },
    { from: 'planSearch', to: 'confluenceSearch' },
    { from: 'planSearch', to: 'jiraSearch' },
    { from: 'adoSearch', to: 'synthesize' },
    { from: 'confluenceSearch', to: 'synthesize' },
    { from: 'jiraSearch', to: 'synthesize' },
    { from: 'synthesize', to: 'refineChat' },
    { from: 'refineChat', to: 'writeReport' },
    { from: 'refineChat', to: 'slackNotify' },
  ],
  variables: {
    configPath: 'data/Jira/config/jira.env',
    changeTitle: '',
    changeDescription: '',
    affectedAreas: '',
    timeline: '',
    additionalContext: '',
    model: 'sonnet',
    adoConfigPath: 'data/ADO/config/ado.env',
    adoRepoUrl: '',
    confluenceSearchQuery: '',
    confluenceSpaceKey: '',
    jiraSearchJql: '',
    outputPath: 'data/Output/Impact-Analysis/change-impact-report.md',
    slackWebhookUrl: '',
  },
};

// ============================================
// Getting Started templates (no credentials required)
// ============================================

export const AI_BRAINSTORM_TEMPLATE: WorkflowGraph = {
  id: 'ai-brainstorm',
  name: 'AI Brainstorm',
  description: 'No credentials needed. Describe a topic and AI generates a structured brainstorm with ideas, pros/cons, and next steps. Great for trying Workflow Studio for the first time.',
  category: 'Getting Started',
  nodes: [
    {
      id: 'topic',
      type: 'transform.template',
      label: 'Define Topic',
      position: { x: 40, y: 80 },
      config: {
        template: '{{vars.topic}}',
      },
    },
    {
      id: 'brainstorm',
      type: 'ai.runPrompt',
      label: 'AI Brainstorm',
      position: { x: 320, y: 80 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 120000,
        prompt: [
          'You are a creative strategist. Brainstorm the following topic thoroughly.',
          '',
          'TOPIC: {{topic.content}}',
          '',
          'Produce a structured brainstorm with these sections:',
          '',
          '## Ideas',
          'Generate 5-8 creative ideas or approaches.',
          '',
          '## Pros & Cons',
          'For the top 3 ideas, list key advantages and disadvantages.',
          '',
          '## Recommended Approach',
          'Suggest which idea (or combination) is strongest and why.',
          '',
          '## Next Steps',
          'List 3-5 concrete next actions to move forward.',
        ].join('\n'),
      },
    },
    {
      id: 'review',
      type: 'ai.interactiveChat',
      label: 'Review & Refine',
      position: { x: 600, y: 80 },
      config: {
        model: '{{vars.model}}',
        maxTurns: 20,
      },
    },
    {
      id: 'save',
      type: 'io.writeFile',
      label: 'Save Result',
      position: { x: 880, y: 80 },
      config: {
        path: '{{vars.outputPath}}',
        content: '{{review.text}}',
      },
    },
  ],
  edges: [
    { from: 'topic', to: 'brainstorm' },
    { from: 'brainstorm', to: 'review' },
    { from: 'review', to: 'save' },
  ],
  variables: {
    topic: 'How to improve developer onboarding at a mid-size startup',
    model: 'sonnet',
    outputPath: 'data/Output/brainstorm.md',
  },
};

export const AI_DOCUMENT_WRITER_TEMPLATE: WorkflowGraph = {
  id: 'ai-document-writer',
  name: 'AI Document Writer',
  description: 'No credentials needed. Write any document (RFC, design doc, meeting notes, blog post) from a spec. AI drafts the full document, you review and refine interactively, then save.',
  category: 'Getting Started',
  nodes: [
    {
      id: 'spec',
      type: 'spec.input',
      label: 'Document Spec',
      position: { x: 40, y: 80 },
      config: {
        title: '{{vars.docTitle}}',
        objective: '{{vars.docObjective}}',
        scope: '',
        constraints: '',
        acceptanceCriteria: '',
        deliverables: '',
        notes: '',
      },
    },
    {
      id: 'draft',
      type: 'ai.runPrompt',
      label: 'AI Draft',
      position: { x: 320, y: 80 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 180000,
        prompt: [
          'Write a professional document based on this specification.',
          '',
          '{{spec.specText}}',
          '',
          'Requirements:',
          '- Use clear, professional markdown formatting',
          '- Include a title, introduction, main sections, and conclusion',
          '- Be thorough but concise',
          '- Use bullet points and tables where appropriate',
        ].join('\n'),
      },
    },
    {
      id: 'review',
      type: 'ai.interactiveChat',
      label: 'Review & Refine',
      position: { x: 600, y: 80 },
      config: {
        model: '{{vars.model}}',
        maxTurns: 20,
      },
    },
    {
      id: 'save',
      type: 'io.writeFile',
      label: 'Save Document',
      position: { x: 880, y: 80 },
      config: {
        path: '{{vars.outputPath}}',
        content: '{{review.text}}',
      },
    },
  ],
  edges: [
    { from: 'spec', to: 'draft' },
    { from: 'draft', to: 'review' },
    { from: 'review', to: 'save' },
  ],
  variables: {
    docTitle: 'Technical Design Document',
    docObjective: 'Describe the architecture and implementation plan',
    model: 'sonnet',
    outputPath: 'data/Output/document.md',
  },
};

export const AI_CODE_REVIEWER_TEMPLATE: WorkflowGraph = {
  id: 'ai-code-reviewer',
  name: 'AI Code Review',
  description: 'No credentials needed. Paste code into a file, and AI performs a thorough code review covering bugs, security, performance, and style. Review and refine the feedback interactively.',
  category: 'Getting Started',
  nodes: [
    {
      id: 'code',
      type: 'io.readFile',
      label: 'Read Code',
      position: { x: 40, y: 80 },
      config: {
        path: '{{vars.codePath}}',
      },
    },
    {
      id: 'reviewAi',
      type: 'ai.runPrompt',
      label: 'AI Review',
      position: { x: 320, y: 80 },
      config: {
        model: '{{vars.model}}',
        timeoutMs: 180000,
        prompt: [
          'You are a senior software engineer performing a thorough code review.',
          '',
          'CODE TO REVIEW:',
          '```',
          '{{code.content}}',
          '```',
          '',
          'Review this code and provide feedback in these categories:',
          '',
          '## Bugs & Correctness',
          'Any logic errors, edge cases, or potential runtime failures.',
          '',
          '## Security',
          'Injection risks, auth issues, data exposure, OWASP concerns.',
          '',
          '## Performance',
          'Inefficiencies, unnecessary allocations, N+1 queries, etc.',
          '',
          '## Code Quality',
          'Readability, naming, structure, DRY violations, error handling.',
          '',
          '## Positive Notes',
          'What is done well — call out good patterns.',
          '',
          '## Summary',
          'Overall assessment and top 3 priority items to address.',
        ].join('\n'),
      },
    },
    {
      id: 'refine',
      type: 'ai.interactiveChat',
      label: 'Discuss Findings',
      position: { x: 600, y: 80 },
      config: {
        model: '{{vars.model}}',
        maxTurns: 20,
      },
    },
    {
      id: 'save',
      type: 'io.writeFile',
      label: 'Save Review',
      position: { x: 880, y: 80 },
      config: {
        path: '{{vars.outputPath}}',
        content: '{{refine.text}}',
      },
    },
  ],
  edges: [
    { from: 'code', to: 'reviewAi' },
    { from: 'reviewAi', to: 'refine' },
    { from: 'refine', to: 'save' },
  ],
  variables: {
    codePath: '',
    model: 'sonnet',
    outputPath: 'data/Output/code-review.md',
  },
};

export function getStudioTemplates(): WorkflowGraph[] {
  return [AI_BRAINSTORM_TEMPLATE, AI_DOCUMENT_WRITER_TEMPLATE, AI_CODE_REVIEWER_TEMPLATE, JIRA_PLAN_TEMPLATE, JIRA_RESEARCH_TEMPLATE, JIRA_RESEARCH_ADO_TEMPLATE, JIRA_RESEARCH_GUIDE_TEMPLATE, JIRA_REVIEW_REFINE_TEMPLATE, JIRA_TICKET_GENERATOR_TEMPLATE, JIRA_TICKET_GENERATOR_PR_TEMPLATE, JIRA_TICKET_TO_CODE_TEMPLATE, JIRA_SPEC_TO_CODE_TEMPLATE, DEEP_RESEARCH_TEMPLATE, INCIDENT_RESPONSE_TEMPLATE, SPRINT_REPORT_TEMPLATE, CHANGE_IMPACT_TEMPLATE];
}
